### ISSUE TITLE
Follow-up Tasks for MachinePool support in ClusterClass

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api#10028]
### What would you like to be added (User Story)?

This is a follow up to #5991 to track the remaining follow-up tasks for adding MachinePool support in ClusterClass.

### Detailed Description

```[tasklist]
### Unit Tests
- [x] internal/controllers/topology/cluster/scope/state_test.go #10052 @willie-yao
- [x] internal/controllers/topology/cluster/scope/upgradetracker_test.go #10052 @willie-yao
- [x] internal/topology/check/compatibility_test.go #10052 @willie-yao
- [x] internal/webhooks/cluster_test.go #10055 @willie-yao
- [x] internal/webhooks/clusterclass_test.go #10055 @willie-yao
- [x] internal/webhooks/patch_validation_test.go #10055 @willie-yao
- [x] internal/controllers/clusterclass/clusterclass_controller_test.go #10055 @willie-yao
- [x] test/extension/handlers/topologymutation/handler_test.go #10216 @willie-yao
- [x] cmd/clusterctl/client/cluster/topology_test.go #10216 @willie-yao
- [x] Run unit & integration tests with coverage and check if we missed something
```

```[tasklist]
### E2E Tests
- [x] ClusterClass changes & rollout (clusterclass_changes.go & clusterclass_rollout, flavor: "topology") #9703
- [x] clusterctl upgrade (clusterctl_upgrade.go, workload flavor: "topology") #9892
- [x] Runtime SDK (cluster_upgrade_runtimesdk.go, flavor: "upgrades-runtimesdk") #9703
- [x] Self-hosted (self_hosted.go, flavor: "topology") #9540
- [x] Autoscaler (autoscaler.go, flavor: "topology-autoscaler") #10083
- [x] Audit if there are any Cluster YAMLs left in the test folder which don't have a machinePool in Cluster.spec.topology
```

```[tasklist]
### Misc/Documentation
- [x] Update proposal #10418
- [x] Update docs (probably mostly book) #10418
```

```[tasklist]
### Non-blocking for MP Graduation
- [x] Dualstack e2e tests #10135
- [x] TBD: internal/controllers/topology/machinepool might be not needed as MachinePool.reconcileDelete deletes templates
```

### Later

- TBD: consider de-duplicating MD/MP code
- TBD: MachinePool upgrading use Node list instead of Node get
- MHC for MachinePools: depends on MachinePool Machines

### Label(s) to be applied

/kind feature

**Comment by sbueringer** [comment]
/triage accepted

Would be really nice to get the test coverage for MachinePools

**Comment by willie-yao** [comment]
> Would be really nice to get the test coverage for MachinePools

Apologies for the delay, it's next on my list!

**Comment by sbueringer** [comment]
No worries :) Thank you very much!

**Comment by willie-yao** [comment]
Update: We decided in office hours that we should fix the flakes in the dualstack test for MachineDeployments before implementing them for MachinePools. Therefore, the dualstack test for MachinePools will be non-blocking for MachinePool graduation.

**Comment by willie-yao** [comment]
> Run unit & integration tests with coverage and check if we missed something

Verified that all instances of MP support in existing files related to ClusterClass have test coverage.

**Comment by willie-yao** [comment]
> Audit if there are any Cluster YAMLs left in the test folder which don't have a machinePool in Cluster.spec.topology

Verified all templates inside `test/e2e/data/infrastructure-docker/main` besides the dualstack specs include MachinePools in the topology.

**Comment by willie-yao** [comment]
@sbueringer Are we good to close this issue? All defined tasks have been completed!
