### ISSUE TITLE
Tasks for v1.8.0 release cycle

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#10472]
Please see the corresponding section in [release-tasks.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.
* The following is based on the v1.8 release cycle. Modify according to the tracked release cycle.

Week 1:
* [x] [Release Lead] [Cut the v1.7.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Finalize release schedule and team](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#finalize-release-schedule-and-team)
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/10490
* [x] [Release Lead] [Add/remove release team members](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#addremove-release-team-members)
  * OWNERS PR: https://github.com/kubernetes-sigs/cluster-api/pull/10473
  * org PR: https://github.com/kubernetes/org/pull/4895
  * community PR: https://github.com/kubernetes/community/pull/7842
* [x] [Release Lead] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
  * PR: #10524
* [x] [Communications Manager] [Add docs to collect release notes for users and migration notes for provider implementers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers)
   * PR: https://github.com/kubernetes-sigs/cluster-api/pull/10528
* [x] [Communications Manager] [Update supported versions](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions)
   * PR: https://github.com/kubernetes-sigs/cluster-api/pull/10529

Week 1 to 4:
* [x] [Release Lead] [Track] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-remove-previously-deprecated-code)

Week 6:
* [x] [Release Lead] [Cut the v1.7.2 & v1.6.5 releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 9:
* [x] [Release Lead] [Cut the v1.7.3 & v1.6.6 releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 10-11:
* [x] [Release Lead] [Track] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-bump-dependencies)

Week 12:
* [x] [Release Lead] [Cut the v1.7.4 & v1.6.7 releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 13:
* [x] [Release Lead] [Cut the v1.8.0-beta.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Create a new GitHub milestone for the next release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-new-github-milestone-for-the-next-release)
* [x] [Communications Manager] [Communicate beta to providers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#communicate-beta-to-providers)

Week 14:
* [x] [Release Lead] [Cut the v1.8.0-beta.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Set a tentative release date for the next minor release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#set-a-tentative-release-date-for-the-next-minor-release)
   * PR: https://github.com/kubernetes-sigs/cluster-api/pull/10930
* [x] [Release Lead] [Assemble next release team](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#assemble-next-release-team)
* [x] [Release Lead] Select release lead for the next release cycle

Week 15:
* [x] [Release Lead] [Cut the v1.8.0-rc.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Update milestone applier and GitHub Actions](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-milestone-applier-and-github-actions)
  * [x] https://github.com/kubernetes/test-infra/pull/33163
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/10963 
* [x] [CI Manager] [Setup jobs and dashboards for the release-1.8 release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch)
  * [x] https://github.com/kubernetes/test-infra/pull/33156
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/10964
* [x] [Communications Manager] [Ensure the book for the new release is available](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#ensure-the-book-for-the-new-release-is-available)
  * [x] https://github.com/kubernetes/k8s.io/pull/7094
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/10960

Week 16:
* [x] [Release Lead] [Cut the v1.8.0-rc.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 17:
* [x] [Release Lead] [Cut the v1.8.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.7.5 & v1.6.8 releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Organize release retrospective
* [x] [Communications Manager] [Change production branch in Netlify to the new release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#change-production-branch-in-netlify-to-the-new-release-branch)
* [x] [Communications Manager] [Update clusterctl links in the quickstart](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-clusterctl-links-in-the-quickstart)

Continuously:
* [Release lead] [Maintain the GitHub release milestone](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-maintain-the-github-release-milestone)
* [Release lead] [Bump the Go version](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bump-the-go-version)
* [Communications Manager] [Communicate key dates to the community](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-communicate-key-dates-to-the-community)
* [Communications Manager] Improve release process documentation
* [Communications Manager] Maintain and improve user facing documentation about releases, release policy and release calendar
* [CI Manager] [Monitor CI signal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-monitor-ci-signal)
* [CI Manager] [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)
* [CI Manager] [Bug triage](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bug-triage)
* [CI Manager] Maintain and improve release automation, tooling & related developer docs

If and when necessary:
* [x] [Release Lead] [Track] [Bump the Cluster API apiVersion](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-bump-the-cluster-api-apiversion)
* [x] [Release Lead] [Track] [Bump the Kubernetes version](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-bump-the-kubernetes-version)
* [x] [Release Lead] [Track Release and Improvement tasks](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-release-and-improvement-tasks)

**Comment by Nivedita-coder** [comment]
Hey @adilGhaffarDev,
I would like to do `Prepare main branch for development of the new release` task! :)

**Comment by chandankumar4** [comment]
Add docs to collect release notes for users and migration notes for provider implementers - PR https://github.com/kubernetes-sigs/cluster-api/pull/10528
Update supported versions - PR https://github.com/kubernetes-sigs/cluster-api/pull/10529
@adilGhaffarDev

**Comment by sbueringer** [comment]
@adilGhaffarDev fyi, I created the milestone ("[Create a new GitHub milestone for the next release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-new-github-milestone-for-the-next-release)")

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev fyi, I created the milestone ("Create a new GitHub milestone for the next release")

Yes I checked it last week and it was already there, thank you.

**Comment by sbueringer** [comment]
@adilGhaffarDev @chandankumar4 @vishalanarase Please use ^^ for the upcoming release notes. I'll update when some new relevant changes are merged

**Comment by sbueringer** [comment]
If I see correctly the milestone applier PR is missing

**Comment by sbueringer** [comment]
@adilGhaffarDev I added a few links, but can you please edit the issue description to link all related PRs to the corresponding sub-tasks? Makes it possible / a lot easier to verify that we didn't forget anything

**Comment by sbueringer** [comment]
Highlights for the upcoming release (notes) (as of 9th August)

```
# CAPI

## Highlights

- Bumped to controller-runtime v0.18, k8s.io/* v0.30, controller-gen v0.15, Go 1.22
- API: Add support for negative polarity conditions (#10550)
- API: Allow control plane provider to set control plane endpoint (#10667)
- CABPK: Add kubeadm v1beta4 types (including ExtraEnvs and ImagePullSerial) (#10709, #10846)
- CABPK: Allow to generate JoinConfiguration discovery kubeconfig (#10799)
- ClusterClass: Improvements for variables
  - CEL support for variables (#9239)
  - Metadata for top-level and nested variables (& deprecate previous metadata field) (#10778)
  - Support control plane variable overrides (#10682)
  - New builtin variables: control plane / MD / MP metadata (#10837), Cluster UID (#10822)
- KCP: Delete out of date machines with unhealthy control plane component conditions during rollout (#10196)
- KCP: Default ControlPlaneKubeletLocalMode kubeadm feature gate to true for Kubernetes >= 1.31.0
- Logging: Improvements to rollout logs: Cluster topology controller (#10690), KCP controller & webhooks (#10628), MachineDeployment controller (#10688)
- MachineDeployment: Add remediation strategy (#10712)
- MachineSet/Machine: Improvements to Machine deletion
  - Machine deletion skips waiting for volumes detached for unreachable Nodes (#10662)
  - Machine drain ignores terminating Pods earlier for unreachable Nodes (#10706)
  - MachineSet: Fix deletion priority to avoid deleting too many machines (#10087)
  - MachineSet: Deprioritize unknown NodeHealthy conditions for deletion (#10763)
  - MachineSet: Ensure unhealthy machines get deletion priority (#10755)
- A usual, significantly improved e2e test framework & coverage (#10083, #10216, #10135, #10498, #10639, #10530)
- New providers in clusterctl: IONOS Cloud (#10767), Linode (#10471), Tinkerbell (#10487)
 
## Deprecation Warning

- ClusterClass: Deprecate definitionFrom field (#10841)
- ClusterClass: Deprecate IP Family builtin variable (#10554)
- MachineDeployment: Deprecate revision management (#10855)
- MachineHealthCheck: Deprecate MaxUnhealthy & UnhealthyRange fields (#10853)

Umbrella issue: API changes: #10852

```

**Comment by sbueringer** [comment]
@adilGhaffarDev I updated the task list, I think we can close this issue?

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev I updated the task list, I think we can close this issue?

yes, closing.
