### ISSUE TITLE
Tasks to bump to Kubernetes v1.31

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#10653]
This issue is tracking the tasks that should be implemented **after** the Kubernetes minor release has been released.

## Tasks

**Note:** If feasible we usually cherry-pick the changes back to the latest release series.

### Supporting managing and running on the new Kubernetes version (@sbueringer / @chrischdi)

This section contains tasks to update our book, e2e testing and CI to use and test the new Kubernetes version
as well as changes to Cluster API that we might have to make to support the new Kubernetes version. All of these
changes should be cherry-picked to all release series that will support the new Kubernetes version.

* [x] Continuously modify CAPD to use early versions of the upcoming Kubernetes release (betas and rcs):
  * Bump the Kubernetes version in `test/*` except for `test/infrastructure/kind/*`.
  * Prior art: #10384
  * https://github.com/kubernetes-sigs/cluster-api/pull/10922
  * #10965
  * #11021
* [x] Modify CAPD to use the new Kubernetes release after it is GA:
  * Bump the Kubernetes version in `test/*` except for `test/infrastructure/kind/*`.
  * Prior art: #10454
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/11030
* [x] Ensure the jobs are adjusted to provide test coverage according to our [support policy](https://cluster-api.sigs.k8s.io/reference/versions.html#supported-kubernetes-versions):

  PR: https://github.com/kubernetes/test-infra/pull/33294

  * At the `.versions`  section in the `cluster-api-prowjob-gen.yaml` file in [test-infra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/):
    * Add a new entry for the new Kubernetes version
    * Adjust the released Kubernetes's version entry to refer `stable-1.<minor>` instead of `ci/latest-1.<minor>`
    * Check and update the versions for the keys `etcd` and `coreDNS` if necessary:
      * For etcd, see the `DefaultEtcdVersion` kubeadm constant: [e.g. for v1.28.0](https://github.com/kubernetes/kubernetes/blob/v1.28.0/cmd/kubeadm/app/constants/constants.go#L308)
      * For coredns, see the `CoreDNSVersion` kubeadm constant:[e.g. for v1.28.0](https://github.com/kubernetes/kubernetes/blob/v1.28.0/cmd/kubeadm/app/constants/constants.go#L344)
  * For the `.branches.main` section in the `cluster-api-prowjob-gen.yaml` file in [test-infra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/):
    * For the `.upgrades` section:
      * Drop the oldest upgrade
      * Add a new upgrade entry from the previous to the new Kubernetes version
    * Bump the version set at `.kubernetesVersionManagement` to the new minimum supported management cluster version (This is the image version available as kind image).
    * Bump the version set at `.kubebuilderEnvtestKubernetesVersion` to the new minimum supported management cluster version.
  * Run `make generate-test-infra-prowjobs` to generate the resulting prowjob configuration:

    ```sh
    TEST_INFRA_DIR=../../k8s.io/test-infra make generate-test-infra-prowjobs
    ```

  * Prior art: https://github.com/kubernetes/test-infra/pull/32456

* [x] Update book:
  * Update supported versions in `versions.md`
  * Prior art: #10454
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/11030

* [x] Issues specific to the Kubernetes minor release:
  * Sometimes there are adjustments that we have to make in Cluster API to be able to support
    a new Kubernetes minor version. Please add these issues here when they are identified.
  * Consider
    * https://github.com/kubernetes-sigs/cluster-api/issues/10708
      * PR: https://github.com/kubernetes-sigs/cluster-api/pull/10709
      * PR: https://github.com/kubernetes-sigs/cluster-api/pull/10771
    * https://github.com/kubernetes-sigs/cluster-api/issues/10737

### Bump quickstart and kind image references in CAPD

Prerequisites:

* The target Kubernetes version is GA
* There is a new [kind version with/or a new set of kind images](https://github.com/kubernetes-sigs/kind/releases) for the target Kubernetes version

* [x] Bump quickstart and kind image references in CAPD:
  * Bump the Kubernetes version in:
    * `docs/*`
    * `Tiltfile`
  * Bump kind image references in CAPD (and also kind if necessary, including the latest images for this kind release)
    * Add new images in the [kind mapper.go](https://github.com/kubernetes-sigs/cluster-api/blob/0f47a19e038ee6b0d3b1e7675a62cdaf84face8c/test/infrastructure/kind/mapper.go#L79).
      * See the [kind releases page](https://github.com/kubernetes-sigs/kind/releases) for the list of released images.
    * Set new default image for the [test framework](https://github.com/kubernetes-sigs/cluster-api/blob/0f47a19e038ee6b0d3b1e7675a62cdaf84face8c/test/framework/bootstrap/kind_provider.go#L40)
    * If code changes are required for CAPD to incorporate the new Kind version, update [kind latestMode](https://github.com/kubernetes-sigs/cluster-api/blob/0f47a19e038ee6b0d3b1e7675a62cdaf84face8c/test/infrastructure/kind/mapper.go#L66)
  * Verify the quickstart manually
  * Prior art: #10610
  * PR: #11081
* [x] Cherry-pick above PR to the latest release branch.
  * PR: #11084

### Using new Kubernetes dependencies

This section contains tasks to update Cluster API to use the latest Kubernetes Go dependencies and related topics
like using the right Go version and build images. These changes are only made on the main branch. We don't
need them in older releases as they are not necessary to manage workload clusters of the new Kubernetes version or
run the Cluster API controllers on the new Kubernetes version.

* [x] Ensure there is a new controller-runtime minor release which uses the new Kubernetes Go dependencies.
* [x] Update our ProwJobs for the `main` branch to use the `kubekins-e2e` with the correct Kubernetes version via [cluster-api-prowjob-gen.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-prowjob-gen.yaml) and by running `make generate-test-infra-prowjobs`.
  * It is recommended to have one PR for presubmit and one for periodic jobs to reduce the risk of breaking the periodic jobs.
  * Prior art: https://github.com/kubernetes/test-infra/pull/32380
  * PR: https://github.com/kubernetes/test-infra/pull/33367
* [x] Bump the Go version in Cluster API: (if Kubernetes is using a new Go minor version) [does not apply, still Go 1.22]
  * Search for the currently used Go version across the repository and update it
  * We have to at least modify it in: `hack/ensure-go.sh`, `.golangci.yml`, `cloudbuild*.yaml`, `go.mod`, `Makefile`, `netlify.toml`, `Tiltfile`
  * Prior art: #10452
* [x] Bumps in Cluster API repo: https://github.com/kubernetes-sigs/cluster-api/pull/10803
  * controller-runtime & controller-tools
  * conversion-gen via `CONVERSION_GEN_VER` in `Makefile`
* [x] Bump the Kubernetes version used in integration tests via `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile`
  * **Note**: This PR should be cherry-picked as well. It is part of this section as it depends on kubebuilder/controller-runtime releases and is not strictly necessary for [Supporting managing and running on the new Kubernetes version](#supporting-managing-and-running-on-the-new-kubernetes-version).
  * Prior art: #7193
  * Prior art to release envtest binaries: https://github.com/kubernetes-sigs/controller-tools/pull/1032
  * PR: #11085
  * release-1.8 PR: #11086

Follow-ups after CR v0.19 bump:
* [x] Simplify metric queries / Grafana dasbhoards (xref: https://github.com/kubernetes-sigs/controller-runtime/pull/2895)
  * Nothing to do, we only have simple queries in the controller-runtime dashboard like this `workqueue_depth{pod=~"$Pod",name=~"$Controller"}`. We should keep using name there for compatibility with controllers that are using CR versions <= v0.18.x
* [x] Add e2e test coverage to verify via metrics that no panics occured (xref: https://github.com/kubernetes-sigs/controller-runtime/pull/2905): https://github.com/kubernetes-sigs/cluster-api/pull/11066
* [x] Filter out finalizer warnings in controllers (xref: https://github.com/kubernetes-sigs/controller-runtime/pull/2903)
  * Opened an issue: https://github.com/kubernetes-sigs/cluster-api/issues/11065

**Comment by sbueringer** [comment]
/assign @sbueringer 
/assign @chrischdi 

/triage accepted

Nothing to do until ~ July.

**Comment by kranurag7** [comment]
FYI, 1.31 beta is out now. Ref: https://github.com/kubernetes/kubernetes/releases/tag/v1.31.0-beta.0 

Looking forward to help with few things here out of many. :)

**Comment by sbueringer** [comment]
Thx! Let's see how it goes. Not sure about the critical path to get v1.31 support out, because we have a very tight deadline, so I would like to do this closely coordinated with @chrischdi.

But there are a definitely other tasks on this issue that are not in the critical path (they'll be after Kubernetes 1.31 GA and CAPI v1.8.1 though)

**Comment by sivchari** [comment]
> Bump quickstart and kind image references in CAPD

Hi. Can I take this task ?

**Comment by sbueringer** [comment]
This can only be done after the prerequisites are fulfilled:
>Prerequisites:
> * The target Kubernetes version is GA
> * There is a new [kind version with/or a new set of kind images](https://github.com/kubernetes-sigs/kind/releases) for the target Kubernetes version

**Comment by sivchari** [comment]
@sbueringer 
I understood, thanks. When the prerequisites are fulfilled, I'd contribute it. And I'm willing to help with other tasks. :)

**Comment by sbueringer** [comment]
Hey folks,
the following two tasks can be done now:
* Update our ProwJobs for the main branch to use the kubekins-e2e with the correct Kubernetes version
* Bump the Kubernetes version used in integration tests via KUBEBUILDER_ENVTEST_KUBERNETES_VERSION in Makefile

**Comment by sbueringer** [comment]
kind v0.24 was released (https://github.com/kubernetes-sigs/kind/releases/tag/v0.24.0)

So "Bump quickstart and kind image references in CAPD" is also unblocked

**Comment by sbueringer** [comment]
All done

Thx everyone!

/close
