### ISSUE TITLE
Tracking issue for Improving status in CAPI resources - Follow up from phase 1

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#11474]
This is a tracking issue for activities related to #10897
Phase 1 activities are tracked into #11105

### Follow up from phase 1 (1.10)

- [x] Fine tuning of godocs for API types (make them kubectl explain compliant)
        - rif https://github.com/kubernetes-sigs/cluster-api/pull/10897#discussion_r1746863755
        - it seems it is address in latest version of controller-tools (see comment below)
- [x] Extending CC to allow the definition of AvailabilityGates & ReadinessGates (and Cluster topology) https://github.com/kubernetes-sigs/cluster-api/pull/11868
   - rif https://github.com/kubernetes-sigs/cluster-api/pull/10897#discussion_r1692224897
   - rif https://github.com/kubernetes-sigs/cluster-api/pull/11234#discussion_r1784087596
- [x] Consider if to allow users to add arbitrary ReadinessGates to KCP machines https://github.com/kubernetes-sigs/cluster-api/pull/11868
- [x] Rename test types to align to API types (v1Beta2 in the middle) https://github.com/kubernetes-sigs/cluster-api/pull/11832
- [x] ExtensionConfig https://github.com/kubernetes-sigs/cluster-api/pull/11848
- [x] DockerCluster and DockerMachine controllers 
  - [x] https://github.com/kubernetes-sigs/cluster-api/pull/11901
  - [x] https://github.com/kubernetes-sigs/cluster-api/pull/11923
- [x] Add support for negative polarity conditions to ReadinessGates and AvailabilityGates https://github.com/kubernetes-sigs/cluster-api/pull/11918

Dropped
- Check if NodeNetworkUnavailable must be added to MachineNodeHealthyCondition
   - Looks like NodeNetworkUnavailable is a left over of in tree gcp provider
- Allow customisation of remote-conditions-grace-period at cluster level
   - rif https://github.com/kubernetes-sigs/cluster-api/pull/10897#discussion_r1694994792 
- InMemoryCluster and InMemoryMachine controllers
   - It is being merged in CAPD(ev)

**Comment by sbueringer** [comment]
Assigned to v1.10 for now to keep an eye on it. I think it's not clear yet in which release this will land.

**Comment by fabriziopandini** [comment]
WRT to make new API fields kubectl explain compliant (rif https://github.com/kubernetes-sigs/cluster-api/pull/10897#discussion_r1746863755)

New fields introduced by the improve status proposal doesn't have fancy formatting anymore; never the less, it seems that this issue has been addressed in latest version of controller tools:

field with list using *
```
  template      <string>
    template defines the template to use for generating the name of the
    ControlPlane object.
    If not defined, it will fallback to `{{ .cluster.name }}-{{ .random }}`.
    If the templated string exceeds 63 characters, it will be trimmed to 58
    characters and will
    get concatenated with a random suffix of length 5.
    The templating mechanism provides the following arguments:
    * `.cluster.name`: The name of the cluster object.
    * `.random`: A random alphanumeric string, without vowels, of length 5.
```

field with list using -
```
  nodeStartupTimeout    <string>
    nodeStartupTimeout allows to set the maximum time for MachineHealthCheck
    to consider a Machine unhealthy if a corresponding Node isn't associated
    through a `Spec.ProviderID` field.

    The duration set in this field is compared to the greatest of:
    - Cluster's infrastructure ready condition timestamp (if and when available)
    - Control Plane's initialized condition timestamp (if and when available)
    - Machine's infrastructure ready condition timestamp (if and when available)
    - Machine's metadata creation timestamp

    Defaults to 10 minutes.
    If you wish to disable this feature, set the value explicitly to 0.
```

**Comment by fabriziopandini** [comment]
All the work planned for 1.10 is completed (with the exception of MachinePools, but this is a wider discussion)
