### ISSUE TITLE
Umbrella - v1alpha2 retrospective action items

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1438]
During out cluster api f2f in Sept 2019 we had ran through a number of items that we should address. 

- [ ] e2e testing 
- [ ] better + concise documentation
- [ ] Well defined release process 
   - [ ] Define blocking features for a release in plain text
   - [ ] Better release notes including breaking changes 
   - [ ] More releases to test integration points and issues (alpha/beta) 
   - [ ] Docs need to be in place prior to cutting a release 
   - [ ] Outline policies on what is allowed in a backport (be explicit [e.g. n-2]) 
   - [ ] Versioning needs TLC
- [ ] Create a policies doc to help empower the community to enable prototypes for providers w/ demos. 
- [ ] Community engagement 
   - [ ] Help create project roles (PMs, release captain, etc.) 
- [ ] Update personas and use cases documentation (Andy, Sam, Tasha, Mosche)

**Comment by ncdc** [comment]
We are working on e2e testing and docs, and I opened issues for the other items in the list (I'm not sure about the policies doc re demos so I skipped over that - someone can open an issue if desired).

/close
