### ISSUE TITLE
Tracking issue for clusterctl v2 implementation

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1729]
Tracking issue for [clusterctl v2](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191016-clusterctl-redesign.md) work

Initial work based on the [clusterctl POC](https://github.com/fabriziopandini/cluster-api/tree/clusterctl-POC)

POC code walkthrough: [1](https://docs.google.com/presentation/d/1eFPfSterI6wf3CDPAKrWkp5LzjOq1RF8nC2N0YbtQMs/edit?usp=sharing) and [2](https://youtu.be/HRB28FYADTM)

IMPORTANT! Details about the following activity breakdown are available https://docs.google.com/document/d/1rLu1P7Bs6BJ1ZL6aOz3AAWGwQ9N8Q3hle7PC56G11t0/edit?usp=sharing

- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1730 Delete current clusterctl and replace with a new CLI stub; finalize the UX
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1738 Add CRD for clusterctl metadata about installed providers; finalize the API
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1762 Add the low-level library for managing clusterctl configurations with default backend implementation based on viper
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2040 rename config
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1864 implement high-level library and CLI for clusterctl configurations
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1842 Add the low-level library for managing provider's repository 
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1981 add support for local overrides
- [x] [Jiatong] https://github.com/kubernetes-sigs/cluster-api/pull/1909 Implement first backend implementation for repository using Github
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1891 Add the low-level library for managing the component.yaml file read from provider's repositories
- [x] [Arvinderpal] https://github.com/kubernetes-sigs/cluster-api/pull/1963 Add file system backend implementations for provider's repository
- [ ] [low priority] Add more backend implementations for provider's repository backends (HTTP/HTTPS, S3?)
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1898 Add the low-level library for management clusters / handling of providers inventory
  - [x] [Fabrizio] kubernetes-sigs/cluster-api: Pull Request 1986 fix RBAC for multienancy
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1932 Add the high-level library and CLI for init
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2008 fix for init
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2017 install cert-manager
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2027 hack for local testing
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1470 cfg for the hack 
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/716 cfg for the hack
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2075 fix for python 3
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2071 remove --force
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2098 fix the docker provider
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2099 support for the control plane provider
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2206 wait for inventory CRD
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1996 Add the low-level library for managing cluster templates read from provider's repositories
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1975 Allow variables override
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1976 Refactor fix namespace
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2047 Add the high-level library and CLI for cluster templates
        NB.  To be changed vs the POC, rif  https://github.com/kubernetes-sigs/cluster-api/pull/1730#discussion_r346864877
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2211 fix config provider command
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2221 Simplify naming
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2265 Allow cluster templates from user defined repository
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2048 Add the low-level library he high-level library and CLI for config provider <povider-name>
- [x] [Fabrizio] Add the low-level library for Move
        NB.  To be changed vs the POC, rif  https://github.com/kubernetes-sigs/cluster-api/issues/1525
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1977 test framework
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2059 improve test framework
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2060 object graph
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2102 object mover
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2130 Move CLI
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2161 Move shared objects
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2245 Ensure NS 
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2246 Preflight provisioning complete
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2130 Add the high-level library and CLI for Move
        NB.  To be changed vs the POC, see https://github.com/kubernetes-sigs/cluster-api/pull/1730#discussion_r343816668, https://github.com/kubernetes-sigs/cluster-api/pull/1730#discussion_r343817053 
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2078 Add the high-level library and CLI for delete
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2061 Version command (not included in the POC)
- [x] [Fabrizio] Upgrade command (not included in the POC)
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1974 add metadata
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1978 add repository.GetVersions
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2134 upgrade plan
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2178 upgrade plan cmd
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2281 upgrade apply cmd
- [x] Pre pull images
   - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2104 inspect images
- [ ] [Fabrizio] Adopt providers
- [ ] [Arvinderpal] https://github.com/kubernetes-sigs/cluster-api/pull/2236 E2E tests (not included in the POC)
- [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/1994 Review clusterctl docs in the book (not included in the POC)
  - [x] https://github.com/kubernetes-sigs/cluster-api/pull/2175 More docs
- [x] [Fabrizio] Logging
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2150 Add logger
  - CLOSED [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2151 Log Propagation
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2191 Use global logger
- [x] Miscellanea
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2152 fix labels
  - [x] [Fabrizio] https://github.com/kubernetes-sigs/cluster-api/pull/2220 refactor libray

Potential code improvements/cleanups
- https://github.com/kubernetes-sigs/cluster-api/pull/1842#pullrequestreview-329894648 (library layout)
- https://github.com/kubernetes-sigs/cluster-api/pull/1898#discussion_r359496565 (more tests)
- https://github.com/kubernetes-sigs/cluster-api/pull/1932#discussion_r360986828 (audit on API names)
- https://github.com/kubernetes-sigs/cluster-api/pull/1932#discussion_r362025607 (rollback on init)
- https://github.com/kubernetes-sigs/cluster-api/pull/1932#discussion_r363102779 (ensure type imple interface in test --> no consensus yet)
- Done - https://github.com/kubernetes-sigs/cluster-api/pull/1932#discussion_r363106856 (cleanup init retrun params)
- https://github.com/kubernetes-sigs/cluster-api/pull/1932#discussion_r363456323 (cleanup tests)
- Done - https://github.com/kubernetes-sigs/cluster-api/pull/1932#discussion_r363445500 (logs)
- Done - https://github.com/kubernetes-sigs/cluster-api/pull/2102#discussion_r369173921 (logs)
- Done - https://github.com/kubernetes-sigs/cluster-api/pull/2078#discussion_r370851556 (labels/providers names)
- Done - https://github.com/kubernetes-sigs/cluster-api/pull/2078#discussion_r370852004 (labels)

Future work
- Prototype interactive mode for allowing users to set "on-the-fly" the variables to be injected in the yaml for providers components or providers templates 
- Prototype a pluggable template system (vs supporting only variables substitution)

**Comment by fabriziopandini** [comment]
We are done for the upcoming RC, except eventually last minutes changes for the webhooks

/close
🎉 🎉 🎉 🎉 🎉 

https://github.com/kubernetes-sigs/cluster-api/pull/2313, https://github.com/kubernetes-sigs/cluster-api/pull/2314 are small fixes, not blocking for the release.

Clusterctl adopts, E2E tests, and other minor improvements code/cleanup are shifting to the next round.
