### ISSUE TITLE
Tracking issue for e2e testing framework and implementation

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1732]
# Testing framework

Based on the [testing proposal][test proposal] we have a lot of work to do! This issue tracks the work to be done

[test proposal]: https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191016-e2e-test-framework.md

## Initial work to set patterns

- [x] Build framework
  - [x] Collect feedback
  - [x] Merge framework
- [x] Implement CAPD tests

## Parallel work after patterns are in place (in order of priority)

- [x] Automate CAPD tests (#1921)
- [ ] Implement CAPA tests
- [ ] Ensure satisfactory documentation for use
- [x] Design and implement debugging when the environment being run is not accessible (prow). See https://github.com/kubernetes-sigs/cluster-api/pull/1737#discussion_r344799496 for more information.
- [ ] Write tests (see next section) in the framework for each behavior we want tested. Consider consolidating if there is overlap.
- [x] Enable the framework build in CI https://github.com/kubernetes-sigs/cluster-api/issues/1772 (https://github.com/kubernetes-sigs/cluster-api/pull/1771)
- [x] Use go 1.12 instead of 1.13 https://github.com/kubernetes-sigs/cluster-api/issues/1773 (https://github.com/kubernetes-sigs/cluster-api/pull/1778)

### Tests to write in the framework that can be reused

- [x] There is a Kubernetes cluster with one node that passes a healthcheck after creating a properly configured Cluster, InfraCluster, Machine, InfraMachine and BootstrapConfig. (https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/one_node_cluster.go)
- [x] Creating the resources necessary for three control planes will create a three node cluster. (https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/multi_node_control_plane.go)
- [x] Deleting a cluster deletes all resources associated with that cluster including Machines, BootstrapConfigs, InfraMachines, InfraCluster, and generated secrets. (#1915)
- [ ] Creating a cluster with one control plane and one worker node will result in a cluster with two nodes.
- [ ] The version fields in Machines are respected within the bounds of the Kubernetes skew policy.
- [ ] Creating a control plane machine and a MachineDeployment with two replicas will create a three node cluster with one control plane node and two worker nodes.
- [ ] MachineDeployments do their best to keep Machines in an expected state. For example:
  - [ ] Modifying a replica count on a MachineDeployment will modify the number of worker nodes and Machines in running state the cluster has.
  - [ ] Deleting a machine that is managed by a MachineDeployment will be recreated by the MachineDeployment
- [ ] Optionally, Machines report failures when their underlying InfraMachines report failures.
- [ ] Manage multiple workload clusters in different namespaces.
- [ ] Workload Clusters created pass Kubernetes Conformance. Please see CAPA's implementation.

/milestone v0.3.0
/priority important-soon
/assign

**Comment by chuckha** [comment]
Some ideas that came out of https://github.com/kubernetes-sigs/cluster-api/pull/1742

## reduce boilerplate

* Have framework provide a scheme that has the required types registered that the framework uses. This allows implementors to grab that runtime.Scheme and add their own types to it so they don't need to figure out what the framework requires. https://github.com/kubernetes-sigs/cluster-api/pull/1742/files#r345443377
* There is more work to be done around Generators/Components/Dependencies https://github.com/kubernetes-sigs/cluster-api/pull/1742/files#r345447689
  * Least of all would be generating Cluster and Machine objects https://github.com/kubernetes-sigs/cluster-api/pull/1742/files#r345451092

## consistency

* Have the generators/dependencies figure out the version that they need automatically based on the CAPI version being used. https://github.com/kubernetes-sigs/cluster-api/pull/1742/files#r345441607
* Figure out a better way to handle clean up, especially of failed tests https://github.com/kubernetes-sigs/cluster-api/pull/1742/files#r345894500

cc @detiber @wfernandes, thanks for the feedback

**Comment by sb1975** [comment]
What does this mean 
Creating the resources necessary for three control planes will create a three node cluster.

Since MachineDeployments do not support control-plane nodes yet, does this mean presently the three control-plane nodes will be created individually using just "kind: Machine" and not MachineDeployments ?

**Comment by sb1975** [comment]
"Creating a control plane machine and a MachineDeployment with two replicas will create a three node cluster with one control plane node and two worker nodes."
^I guess I already tried this.
In the MachineDeployment yaml file, I just changed the replicas: 2.
It resulted in the target(or workload) cluster with 3 nodes ( 1 master + 2 worker).
I also validated that I can run a nginx pod inside the cluster and it works as expected.

`apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  name: capi-quickstart-worker
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
    # Labels beyond this point are for example purposes,
    # feel free to add more or change with something more meaningful.
    # Sync these values with spec.selector.matchLabels and spec.template.metadata.labels.
    nodepool: nodepool-0
spec:
  replicas: **2**
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capi-quickstart
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: capi-quickstart
        nodepool: nodepool-0
    spec:
      version: v1.15.3
      bootstrap:
        configRef:
          name: capi-quickstart-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: capi-quickstart-worker
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: DockerMachineTemplate
`
root@capd:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig get nodes
NAME                                                      STATUS   ROLES    AGE     VERSION
capi-quickstart-capi-quickstart-controlplane-0            Ready    master   4h6m    v1.15.3
capi-quickstart-capi-quickstart-worker-85cbf8fd8c-mpr2l   Ready    <none>   3h45m   v1.15.3
capi-quickstart-capi-quickstart-worker-85cbf8fd8c-wx75g   Ready    <none>   3h42m   v1.15.3

root@capd:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig get pods -n mynamespace -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP               NODE                                                      NOMINAT                             ED NODE   READINESS GATES
nginx   1/1     Running   0          21m   192.168.61.193   capi-quickstart-capi-quickstart-worker-85cbf8fd8c-mpr2l   <none>                                        <none>

Can I do something more to help this one please ?

**Comment by chuckha** [comment]
@sb1975 I updated the issue to link to the actual tests in the framework as examples to get folks started. Take a look at the existing tests and try to follow the existing patterns or if you find something that needs improving, improve it.

**Comment by wfernandes** [comment]
I'm planning on working on this framework test: _Deleting a cluster deletes all resources associated with that cluster including Machines, BootstrapConfigs, InfraMachines, InfraCluster, and generated secrets._ I'm hoping to pair that work as I accomplish this story #1775.

**Comment by chuckha** [comment]
Closing this in favor of https://github.com/kubernetes-sigs/cluster-api/issues/2141

Other cases are not important right now and will be added in future as importance rises.

/close
