### ISSUE TITLE
Machine Health Checking tracking issue

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#1990]
# Machine Health Checking implementation
Implements https://github.com/kubernetes-sigs/cluster-api/pull/1684
## Foundational patterns
- [x] Merge new types
  - MachineHealthCheck
  - MachineHealthCheckList
  - MachineHealthCheckSpec
  - UnhealthyCondition
  - MachineHealthCheckStatus
- [x] Merge Minimal reconciling skeleton logic unit tested
## Logic Implementation
- [x] Flesh out unit tested reconciler logic to get targets from a MHC resource and health check them.
- [x] Flesh out unit tested remediation logic.
- [x] Add `MachineHealthCheckReconciler` with `SetupWithManager` to `main.go`.
- [x] Add docs
- [x] Add e2e tests

**Comment by vincepri** [comment]
@enxebre do we need to keep this tracking issue open or did you want to close it?

**Comment by enxebre** [comment]
hey @vincepri I think we still need to add e2e tests and docs for MHC, however you prefer to track it works for me.

**Comment by vincepri** [comment]
do you think we can get the documentation and e2e in `v0.3.0` or should we move it to `v0.3.x`?

**Comment by JoelSpeed** [comment]
@vincepri Could you remind me when the cutoff is for `0.3.0`? I'm working on the e2e tests tomorrow and the docs likely later this week, not sure when they'll be ready for merge though

**Comment by vincepri** [comment]
It's set for March 10th, it sounds like we can definitely point this to v0.3.x given that's mostly for testing and docs

**Comment by vincepri** [comment]
Closing this now that all tasks have been completed
/close
