### ISSUE TITLE
CAPD: Use library calls to manage containers rather than calling docker

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api#4380]
**User Story**

As a developer, I would like to make programmatic calls to manage things as much as possible.
As a developer, I would like to be able to unit test my code to ensure proper functionality.
As a user, I would like things to operate smoothly and efficiently.
As an operator, I would like to not have to worry about command line dependencies.

Getting rid of exec'ing out to `docker` for container management should address all of these needs.

**Detailed Description**

We currently call the `docker` CLI to perform our CAPD container management operations. This can be error prone and cause operational and upgrade issues. Ideally we would like to be able to perform these container management operations programmatically without calling out to an independent external executable.

To address this, we should adopt a library for interacting with the container runtime and migrate existing calls to `docker` to use calls from this library instead.

**Anything else you would like to add:**

Some work along this front had been started with https://github.com/kubernetes-sigs/cluster-api/pull/2682. That may not be the implementation path we take, but it should at least give a good example of the kinds of things that need to be done.

**Implementation plan:**

- [x] Remove exec calls out to docker CLI to use API instead
- [x] Refactor docker API code to be behind an abstraction to isolate implementation details
- [ ] Add unit test coverage for code that interacts with container management interface

/kind feature

**Comment by vincepri** [comment]
Should we split up the unit test item in another issue (or set of issues)?

**Comment by stmcginnis** [comment]
Either way works for me. I am hoping to get to that last step soon. Just been tied up lately with some other things, but should have some time over the next couple weeks (I hope).

**Comment by fabriziopandini** [comment]
+1 to small actionable issues
As soon as we get some unit test as examples, then it will be easier to get help from the community as well

**Comment by mdbooth** [comment]
I've just come across this because I've hit a hard dependency on docker. The dependency breaks me because I'm using podman. The specific code which breaks me is https://github.com/kubernetes-sigs/cluster-api/blob/36d4d2eede00c84774296ea8cec0b1db9c196cc2/test/framework/bootstrap/kind_util.go#L159

The code comment claims that the code in question was copied from kind https://github.com/kubernetes-sigs/kind/blob/v0.7.0/pkg/cmd/kind/load/docker-image/docker-image.go#L168. However, the kind code uses the docker cli, which podman is compatible with. The regression was introduced by https://github.com/kubernetes-sigs/cluster-api/pull/4499.

Please could we halt any move towards relying on direct communication with the proprietary docker agent on the host? I don't currently see a good way round this, so I'm going to have to carry a local patch to run tests.

**Comment by stmcginnis** [comment]
Looks like that comment should have been updated.

The only additional work is to get testing in place, so that shouldn't cause any further challenge for your case. There was some (very) long term discussion on supporting other container runtimes. Things should be in place to at least enable that, though it would take some work to get things implemented for other runtimes.

Is there an SDK/API for podman, similar to what is being done with the Docker API?

**Comment by mdbooth** [comment]
I don't understand. Sure the comment needs to be updated and testing is required, but surely neither of those are going to fix the regression introduced by #4499?

I don't know about an SDK for podman, however I do know that podman treats the docker cli as a defacto API and aims for compatibility with it. It obviously can't be compatible with the proprietary host agent, though, because it doesn't have or need one.

What's the context behind the move away from just using the cli? Note that this specific case is running on the host. Surely any host which is running docker's proprietary host agent can also trivially have the cli tool on it?

**Comment by mdbooth** [comment]
Eurgh, the reverts are huge and full of conflicts :( Today isn't a good day. I just want to be able to run my tests.

**Comment by mdbooth** [comment]
Incidentally, the specific error is:

```
[1]       Failed to load image "gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:e2e" into the kind cluster "capo-e2e": error saving image "gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:e2e" to "/tmp/image-tar3240993989/image.tar": unable to read image data: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/get?names=gcr.io%2Fk8s-staging-capi-openstack%2Fcapi-openstack-controller%3Ae2e": dial unix /var/run/docker.sock: connect: permission denied
```

AFAICT this is caused by the prior save, not the push to kind.

**Comment by fabriziopandini** [comment]
@mdbooth I’m really sorry the CAPI framework does not work locally for you, but I’m not sure that this should be accounted to this effort, because even before the test framework was shelling out to the docker CLI, thus still relying on docker being installed on the machine.

Nevertheless I will be more than happy to open a separated issue and track an effort for adding support for running our tests on different developer setups, either as experimental (without guarantees) or as something that we monitor via some CI signal + we quote in our documentation, but this will require some work ...

**Comment by stmcginnis** [comment]
Looking at the libepodman apiv2 work, it looks like that could provide a low friction way to support podman with the docker compatibility APIs. I have not been following that project, so not sure the current status of this (looks like it is still being developed in a feature branch), but once available, it could be a matter of just setting some environment variables so `client.from_env()` knows to connect to tcp:127.0.0.1:5000, for example.

**Comment by mdbooth** [comment]
This isn't the case, because podman provides a compatible docker cli tool, which is why I characterised this as a regression.

**Comment by mdbooth** [comment]
The critical point here is: calling the docker cli works with podman. Directly calling the proprietary docker host agent does not.

**Comment by stmcginnis** [comment]
On the other hand, a CLI is not an API, so that is not a very good integration interface. I understand it does not help in your case, since it was providing a convenient way to swap things out under the hood, but calling out to a CLI as was being done really should be avoided if possible.

**Comment by mdbooth** [comment]
It's a widely used and well understood interface, which is why podman is compatible with it. If we could go back to it until there's an alternative that would be helpful.

**Comment by vincepri** [comment]
Hey folks, we should probably use a different issue to discuss `podman` specific support for the test framework (and what about CAPD?).

When we started this work back in March folks have asked for feedback during the office hours and in this issue. The benefit of removing the dependency from the command line (shelling out) and introduce integration and unit tests was a good strong point in our efforts towards stability.

The codebase never made any compatibility promises to anything other than docker. It seems there is a couple of ways support for another CRI can be introduced over time: 

- Test the current implementation with podman compatibility REST layer.
- Add support for podman using their own APIs.

Let's also chat at the office hours meeting tomorrow.

**Comment by mdbooth** [comment]
Unfortunately I'm unlikely to be able to attend that meeting for most of the year. Possibly if it was an hour earlier?

To be clear, I'm discussing podman support here because it's this effort which appears to have regressed it. I can confirm that the code in kind which was originally copied works fine.

**Comment by vincepri** [comment]
@mdbooth We should track support in a more official manner in a new feature request/issue. The test framework and CAPD never explicitly supported any other CRI other than docker, which is why we're considering it as a new feature rather than a regression.

**Comment by stmcginnis** [comment]
Filed a tracking issue here: https://github.com/kubernetes-sigs/cluster-api/issues/5146
