### ISSUE TITLE
Umbrella: Documentation pre-print requirements

### ISSUE THREAD

**Issue by davidewatson** [kubernetes-sigs/cluster-api#571]
The Cluster API documentation may always continue to be improved. The following tasks are necessary for complete coverage.

## Required:

- [x] Decide Firebase vs. gh-pages vs netify.
- [x] Create architectural diagram for CRDs (https://github.com/kubernetes-sigs/cluster-api/issues/786).
- [x] Create kubectl/controller/actuator/etc. logic traces (https://github.com/kubernetes-sigs/cluster-api/issues/787).
- [ ] Document MachineSet, MachineDeployment, and MachineClass (https://github.com/kubernetes-sigs/cluster-api/issues/788).
- [x] D~ecide whether we want to d~ocument clusterctl (https://github.com/kubernetes-sigs/cluster-api/issues/789).

## Really wanted:

- [ ] Provide guidence on how a provider should indicate to other processes that a Machine has been provisioned.
- [ ] Document resync period and how providers can be notified of external events.
- [ ] Machine documentation for the case where there are _manager_ and _managed_ clusters (cf. https://github.com/kubernetes-sigs/cluster-api/issues/520).

**Comment by davidewatson** [comment]
The only remaining item for this issue is #788. Therefore we are closing it.

/close
