### ISSUE TITLE
Housekeeping tasks for Kubernetes v1.23

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5793]
Let's upgrade to Kubernetes v1.23.

### Tasks

* Make sure we're using a controller-runtime version which uses v1.23: will be done in https://github.com/kubernetes-sigs/cluster-api/issues/5576
* [x] Upgrade testing & CAPD for Kubernetes v1.23:
    * docker.yaml, kind_provider.go, docker/Dockerfile, docker/machine.go, docker/examples/*
* [x] Update testgrid for Kubernetes v1.23
    * cluster-api-periodics-main.yaml (similar for cluster-api-periodics-release-1-0.yaml)
        * periodic-cluster-api-e2e-upgrade-v1-0-to-main: `INIT_WITH_KUBERNETES_VERSION`: `v1.22.0` => `v1.23.0`
    * cluster-api-periodics-main-upgrades.yaml (similar for cluster-api-periodics-release-0-4-upgrades.yaml and cluster-api-periodics-release-1-0-upgrades.yaml)
        * periodic-cluster-api-e2e-workload-upgrade-1-23-latest-main: should be created (based on `...1-22-latest-main`)
        * periodic-cluster-api-e2e-workload-upgrade-1-22-latest-main: rename to `...1-22-1-23-main` + `KUBERNETES_VERSION_UPGRADE_TO`: `ci/latest-1.23` => `stable-1.23`
    * cluster-api-presubmits-main.yaml (similar for cluster-api-presubmits-release-0-4.yaml and cluster-api-presubmits-release-1-0.yaml)
        *  pull-cluster-api-e2e-workload-upgrade-1-22-latest-main: rename to `...1-23-latest-main` + `KUBERNETES_VERSION_UPGRADE_FROM`: `stable-1.22` => `stable-1.23` + `KUBERNETES_VERSION_UPGRADE_TO`: `ci/latest-1.23` => `ci/latest-1.24`
    * Switch images for main Jobs to `-1.23`

* [x] Upgrade quickstart for Kubernetes v1.23 
* [x] Update documention in the core repo
    * Update job documentation accordingly
    * Adapt supported versions in CAPI book

Q: Supported etcd version on main is v3.5.1 for v1.23 **and** v1.22. (https://github.com/kubernetes/kubernetes/blob/v1.23.0-rc.1/cmd/kubeadm/app/constants/constants.go). The latest v1.22.4 release still has v3.5.0. Which version should we use for our v1.22 installations?

/kind feature

**Comment by sbueringer** [comment]
@fabriziopandini Can you check if I missed anything? (P.S. I intentionally didn't document minor changes in Jobs like changing the tab names)

**Comment by fabriziopandini** [comment]
> Can you check if I missed anything? 

Seems ok to me

**Comment by sbueringer** [comment]
I've opened both PRs. Should be ready to go once Kubernetes 1.23 has been released.

**Comment by sbueringer** [comment]
P.S. for 1.24 we can probably use this issue as template + the two corresponding PRs
