### ISSUE TITLE
Tasks for Kubernetes v1.24

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5968]
This issue is tracking the list of tasks that should be implemented when Kubernetes v1.24 is released. **Currently, we are waiting for the Kubernetes release**

* CI:
    * [x] CAPD: #6513
        * `docker.yaml`: `KUBERNETES_` env vars in `variables`
        * kind_provider.go, docker/*, ... (just grep for the previously used version in CAPD)
    * [x] Jobs: https://github.com/kubernetes/test-infra/pull/26196
        * Add new periodic upgrade jobs, for all release where we want to support the new Kubernetes version
        * Adjust presubmit jobs so that we have the latest upgrade jobs available on PRs (for all releases)
        * Update `INIT_WITH_KUBERNETES_VERSION`

* [x] Book:
    * [x] Update supported versions in versions.md #6543
    * [x] Update and test quickstart #6513
    * [x] Update job documentation in CAPI (`jobs.md`) #6567

* [x] Release specific issues:
    * [x] [Label/ taint handling for 1.24 mentioned in Rename references to "node-role.kubernetes.io/master" #3279](https://github.com/kubernetes-sigs/cluster-api/issues/3279)
      * [x] PR(main): https://github.com/kubernetes-sigs/cluster-api/pull/5919
      * [x] PR(release-1.1): https://github.com/kubernetes-sigs/cluster-api/pull/6084
      * [x] Let's add notes to our releases about label/taint changes #6543
    * [x] [Handle kubeadm 1.24 kubelet ConfigMap name change #5921](https://github.com/kubernetes-sigs/cluster-api/issues/5921)
      * [x] PR(main): https://github.com/kubernetes-sigs/cluster-api/pull/6176
      * [x] PR(release-1.1): https://github.com/kubernetes-sigs/cluster-api/pull/6206
    * [x] [Use socket with unix:/// in CAPD. #6155](https://github.com/kubernetes-sigs/cluster-api/issues/6155)
      * [x] Use socket with unix:/// in CAPD
      * [x] Document that users should migrate (1. in https://github.com/kubernetes-sigs/cluster-api/issues/6155#issuecomment-1049109302) #6543
    * [x] [Make sure kubeadm 1.24 socket auto-discovery doesn't lead to issues #5920](https://github.com/kubernetes-sigs/cluster-api/issues/5920)
    * [x] Check if contextual logging is merged in the klog version we will upgrade to. If yes migrate to `klog.Background()`
      * xref: https://github.com/kubernetes/klog/issues/302#issuecomment-1048555820 https://github.com/kubernetes/klog/pull/296
        * [x] PR: #6602

* After a Kubernetes release is cut a controller-runtime version is created. When the CR version is available we have to:
    * [x] Use new Kubernetes Go libraries (controller-runtime, controller-tools, client-go, ...)
        * This can include upgrading the Go version (we're using the same as k/k)
        * [x] PR:  #6467 
        * [x] PR: #6542
        * [x] Upgrade to controller-runtime v0.12.2 #6650 
    * [x] Update `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile`
        * [x] PR to bump kubebuilder tools: https://github.com/kubernetes-sigs/kubebuilder/pull/2709
        * [x] follow-up: CAPI PR: #6604
    * [x] If the new Kubernetes version uses a new Go version
        * [x] Jobs: Update kubekins-e2e images used for jobs running against main
            * Potentially it makes sense to switch to the latest ("master") version of kubekins-e2e if there is no `-{KUBERNETES-VERSION}` tag of the image already.
            * PRs: https://github.com/kubernetes/test-infra/pull/26155 & https://github.com/kubernetes/test-infra/pull/26156
            * Follow-up PR in CAPI: #6601
        * [x] Update go version: #6616
            * .github/workflows
            * Tiltfile
            * Makefiles
            * hack/ensure-go.sh
            * netlify.toml
            * [opt] go.mod files (only if we want to increase the minimum supported version of consumers) [DOES NOT APPLY]
        * [x] Update go version:
            * [x] cloudbuild YAMLs (to use an image with the current go version)
                * test-infra PR: https://github.com/kubernetes/test-infra/pull/26540
                * CAPI PR: #6617
            * [x] .golangci.yml (+ corresponding workflow file)
                * for golangci-lint we have to wait for the next release which has a fix for https://github.com/kubernetes-sigs/cluster-api/issues/6350 + Go 1.18 support

**Comment by sbueringer** [comment]
Added a task above to switch to `klog.Background()` with 1.24 if possible.

**Comment by killianmuldoon** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/6467 for controller runtime and k8s dependencies update.

**Comment by jayesh-srivastava** [comment]
Hi @sbueringer if the issue is still open and someone isn't already, can I work on updating the go version in github/workflows, .golangci.yml, Tiltfile, Makefiles etc?

**Comment by sbueringer** [comment]
Hey @jayesh-srivastava,
I'm currently working together with @palnabarun to get the final sub-tasks done.

**Comment by sbueringer** [comment]
Now only golangci-lint bump is left

**Comment by killianmuldoon** [comment]
golangci-lint bump now being tracked in https://github.com/kubernetes-sigs/cluster-api/pull/6737

**Comment by sbueringer** [comment]
All tasks are done :tada: 

Thx very much to @oscr and @killianmuldoon for implementing the golangci-lint bump!!

/close
