### ISSUE TITLE
UMBRELLA: Webhooks / External admission controllers

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#622]
/kind feature

This is a general issue to track the development towards webhoooks in this project and across different cluster api subprojects. 

- [x] Discuss webhooks and plan of action in upcoming (5/12/2018) cluster api meeting.
- [ ] Draw a plan of action for a POC and open new issues to be tracked here.

Some ideas, to be considered just as a starting point:
- [ ] A webhook package should be included in cluster api using [kubebuilder](https://book.kubebuilder.io/beyond_basics/sample_webhook.html).
  - The package must use the manager shared between actuators.
  - The package should offer common primitives to add different kind of webhooks.
  - The package should determine the best possible way to chain different webhooks.
- [ ] Validation webhooks support
- [ ] Mutating webhooks support
- [ ] Conversion webhooks support (i.e. upgrading webhooks)
  - Requires 1.13

Open questions:
- [ ] Should the first version of the package be strict about breaking changes for actuators?
- [ ] Which kind of webhooks should be prioritized?
- [ ] How does this affect one shot deployments?
- [ ] How does the chain of webhook work? Is the order deterministic?

**Comment by alvaroaleman** [comment]
xref https://github.com/kubernetes-sigs/cluster-api/issues/147#issuecomment-430349301

**Comment by vincepri** [comment]
From the docs [here](https://godoc.org/k8s.io/api/admissionregistration/v1beta1#FailurePolicyType) seems you can specify how to handle failures.

**Comment by dlipovetsky** [comment]
@vincepri How does this relate to #471, which is about a "dynamic hook style mechanism for stubbing in actuators?"

(In case the two are related, I have a follow-up question: Are admission (or any other standard Kubernetes) webhooks sufficient for stubbing in actuators? Since webhooks are called when an API object is created/updated/deleted, how could a webhook implement a machine actuator's `Exists` method?)

**Comment by vincepri** [comment]
I don't have the full details on what was discussed in #471 (CC @timothysc @detiber). 

That said, I think they are related. If we go down the webhook route, it should be possible to stub a test actuator for example in a CI job. The question you posed is interesting though, I wonder which parts of the codebase use `Exists` today and if they relate when webhooks are a thing.

**Comment by dlipovetsky** [comment]
I think there are two ways the Cluster API can use webhooks:
1. For validation/defaulting/conversion. These webhooks have well-defined interfaces and are called by the Kubernetes API server.
2. To implement an actuator. I think Cluster API has to define the webhook interface and call it from some controller.

I think this issue is about 1, but #471 might be about 2. Not sure. 

The [machine controller calls](https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L164) `Create` if `Exists` returns false, or `Update` otherwise.

**Comment by hardikdr** [comment]
Wrt #471 - plugging actuators using an extension mechanism.
IMO we need to look at other dimensions as well while coming up with a solution. I recently looked into the CSI model, learned a few bits from there- like gRPC based actuators. There seem to be few benefits in following certain design-principles, such as avoiding kubernetes-specific knowledge in drivers, avoiding kube-access to drivers to achieve homogeneous behavior across cloud and so on. 
I am trying to come up with a proposal doc to outline a few of it soon.

Btw, wondering if it makes sense to maintain a separate issue to discuss the non-webhook based strategies for extension mechanisms [#471], or should this be the place?

**Comment by ncdc** [comment]
@vincepri do you still think we need this as an umbrella issue? Would it be ok to close it and create individual issues as needed?

**Comment by vincepri** [comment]
Sounds good!

/close
