### ISSUE TITLE
Runtime SDK implementation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6330]
Implementation issue for https://github.com/kubernetes-sigs/cluster-api/issues/5175

**Basic Implementation**

Initially we want to add a basic implementation, so we can then work better in parallel on more advanced aspects.

Done:
* [x] Add Extension CRD: (#6383 @killianmuldoon)
    * Extension CRD + Runtime SDK feature flag + webhook which blocks CRD create/update if flag not set
    * corresponding code / manifest
* [x] Implement catalog (~ POC branch without openapi.go / without GVHToPath + more unit tests): (#6393 @ykakarap)
    * tracking hooks, their request/response types and their OpenAPI schemas
    * conversion
* [x] Basic Extension Controller: (#6411 @killianmuldoon)
    * setup in main.go with corresponding concurrency flag
    * alias files + controller skeleton (e.g. SetupWithManager, no code in Reconcile yet)
* [x] Implement registry: (#6449 @sbueringer)
    * thread-safe storage of registry entries (i.e. name, gvh, connection data, namespaceSelector, failurePolicy)
    * registry should be created only once per binary
* [x] Client: Discovery: (#6455 @ykakarap)
    * API package with Discovery types
    * DeepCopy + Conversion code generation
    * Discovery implementation in the Client package
* [x] Extension Controller: Discovery (#6510 @killianmuldoon)
* [x] Client: Calling one and multiple RuntimeExtensions (incl. aggregation) (#6499 @ykakarap @killianmuldoon )
    * [x] [RuntimeSDK: Consider using shared structs in RuntimeHook API types](https://github.com/kubernetes-sigs/cluster-api/issues/6506) (@killianmuldoon) #6499
* [x] Implement aggregation (incl.  introduce RetryableResponse) (#6581 @killianmuldoon @sbueringer)

These are just the first steps, the goal is - as mentioned above - to get the basics in place so we can parallelize better. We have a list of additional aspects we want to address after the basic implementation is done: 

**Additional Tasks** (non-blocking for hook implementations)

Done:
* [x] Advanced defaulting and validation for ExtensionConfig (#6475 @chrischdi)
* [x] Runtime openapi-gen (#6462 @chrischdi)
* [x] Validation of Discovery responses: #6578 (@killianmuldoon)
* [x] Handle ExtensionConfig.spec.namespaceSelector (#6619 @killianmuldoon)
* [x] [RuntimeSDK: seamless certificate handling for RuntimeExtensions](https://github.com/kubernetes-sigs/cluster-api/issues/6507), includes:
    * [x] Implement a final version of http/https support including webhook validation (#6645 @chrischdi)
    * [x] Add index for secret => ExtensionConfig lookup (#6648 @chrischdi)
* [x] Check if/which packages we have to export to enable writing a RuntimeExtension more easily (e.g. catalog)
    * [x] Issue: #6720
* [x] Documentation:
    * [x] [Propagate RuntimeSDK feature flag in docs](https://github.com/kubernetes-sigs/cluster-api/issues/6384) (#6538 @killianmuldoon)
    * [x] Book documentation for RuntimeSDK + hooks (#6756 @sbueringer) 
    * [x] Add disclaimer: clusterctl alpha topology dry run (#6830 @sbueringer)
    * [x] Improve Runtime Hook Swagger documentation (#6878 @fabriziopandini )
* [x] General concerns:
    * [x] metrics (#6675 @chrischdi)
    * [x] error wrapping/context + godoc comments (#6693 @sbueringer)
    * [x] logging (#6832 @ykakarap)
* [x] Testing:
    * [x] Evaluate test & integration test coverage
    * [x] #6907

Cleanup:
* Consider dedup `lowestNonZeroRetryAfterSeconds`: #6945
* Open issue to discuss adding constants for field paths (Cluster/MD/...): see https://github.com/kubernetes-sigs/cluster-api/pull/6289#discussion_r890120475: #6946
* Introduce constants for builtin variable paths: see https://github.com/kubernetes-sigs/cluster-api/pull/6289#discussion_r890124352: #6947

We have some more additional tasks for later in the [Runtime SDK Implementation Design](https://docs.google.com/document/d/1s1Q2emmjflVItf1l1nivvds4rt0gnagWe1jxQq13VH0/edit#heading=h.x0qoac4wlda7)

**Follow-up**:
* #6545
* #6546

/kind feature
