### ISSUE TITLE
Cluster API State Metrics implementation

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#6458]
Follow-up issue to track implementation of the merged proposal 
* #6404

as follow-up to

* #1477

Current state is that the contribution PR needs to be done for https://github.com/mercedes-benz/cluster-api-state-metrics to the `exp/state-metrics` directory which is WIP at the branch https://github.com/mercedes-benz/cluster-api/tree/exp/casm-introduce .

**User Story**
[xref proposal user stories](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220411-cluster-api-state-metrics.md#user-stories)

**TODOs:**

- [x] Proposal: #6404
- [x] ~~Contribution: #6570~~ not necessary, we can directly use kube-state-metrics and the new CustomResource configuration
- [x] Integrate to tilt https://github.com/kubernetes-sigs/cluster-api/pull/7095
- [x] Implement metrics mentioned in the proposal but missing in the current implementation
    - exception: `_labels` metrics
- [x] Implement `cluster_info` including `.spec.controlPlaneEndpoint.host` as label metric to solve #5510 
    - https://github.com/kubernetes-sigs/cluster-api/pull/7095
- [x] ~~clarify and implement steps for image publishing~~
    - not required because we soon can use upstream kube-state-metrics images
- [x] Create issue to clarify and implement release manifest
- [x] resync the proposal to the current state https://github.com/kubernetes-sigs/cluster-api/pull/7183
- [x] review again the *status_*replica* metrics for consistency purposes #7166

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by chrischdi** [comment]
Looks like the kube-state-metrics project made the implementation obsolete.

> https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.5.0 is now available with a lot of great contributions from the community! It comes with more metrics for standard components and an experimental feature to create your own metrics for CRDs! :tada:  Isn't Friday the perfect opportunity to deploy this to your cluster? :wink:

Source: https://kubernetes.slack.com/archives/CJJ529RUY/p1654257314683059

Looks like we should adapt, check if we could do the same with configuration only and deploying kube-state-metrics instead :-)

**Comment by sbueringer** [comment]
Oh, interesting turn of events. Yeah let's figure out if that covers our use case.

**Comment by bavarianbidi** [comment]
As i currently prepare our internal repositories to make use of `cluster-api-state-metrics` and try to propose a generic description to adopt different infrastructure providers as well i just gave `kube-state-metrics` a short try with following config.

```yaml
kind: CustomResourceStateMetrics
spec: 
  resources: 
    - groupVersionKind: 
        group: cluster.x-k8s.io
        kind: Machine
        version: v1beta1
      metrics: 
        - each: 
            path: 
              - status
              - phase
          help: "machine phase"
          name: phase
```

As `kube-state-metrics` expect a `float` as value (https://github.com/kubernetes/kube-state-metrics/blob/7f09ca71ba25af4d2cbb1637e13b28c1d0028159/pkg/customresourcestate/registry_factory.go#L490-L525) above config will fail with

```
E0607 09:12:00.168168  126676 registry_factory.go:469] "kube_cluster_x-k8s_io_v1beta1_Machine_phase" err="[status,phase]: []: strconv.ParseFloat: parsing \"Runn
ing\": invalid syntax"
```

Tried to circumvent the fact that a float is required with following config where i defined the path to the only numbered value field in the `Machine` via

```yaml
kind: CustomResourceStateMetrics
spec: 
  resources: 
    - groupVersionKind: 
        group: cluster.x-k8s.io
        kind: Machine
        version: v1beta1
      metrics: 
        - each: 
            valueFrom:
              - metadata
              - generation
            path: 
              - status
              - phase
          help: "machine phase"
          name: phase
```

But still get an error:

```
E0607 09:12:00.168234  126676 registry_factory.go:469] "kube_cluster_x-k8s_io_v1beta1_Machine_phase_annotation" err="[status,phase]: [metadata,generation]: expe
cted number but found nil value"
```

It seems to me, that a well scoped metrics server for ClusterAPI (+ infrastructure implementations) still make sense.

**Comment by bavarianbidi** [comment]
> Just for my understanding, they only allow exposing floats directly as metrics? So something like the condition metrics just doesn't work?

Exactly, exposing the condition as metric only might work, if at least one numbered field is in the spec (but my hack via `metadata.generation` does not work - so i guess the field must be in the spec or status).

If KSM-folks accept a patch for this and their plans are longer support for this experimental feature this could be a very promising solution for metrics.

**Comment by chrischdi** [comment]
I started a discussion in kube-state-metrics slack : https://kubernetes.slack.com/archives/CJJ529RUY/p1654593034854759 and we will move the discussion to an issue.

For the CAPI project I think we have some options here to continue:
1. wait (and maybe help to reach that point) for kube-state-metrics to enable all kind of metrics via config we want
2. implement custom binary for now:
  a. and migrate to configuration-only kube-state-metrics as soon as all metrics are possible to get defined via configuration (all metrics already possible via config could already get done via config)
  b. and keep custom binary/implementation

**Comment by sbueringer** [comment]
> The time spent moving the code here is probably better invested into kube-state-metrics to get the custom metrics into a suitable replacement.

In general I agree. Depending on how fast we can get the necessary features into kube-state-metrics we could also merge it and then use more and more from the upstream kube-state-metrics until cluster-api-state-metrics is not necessary anymore (as cluster-api-state-metrics imports/extends kube-state-metrics).

But I think for now the best approach is to wait a bit with cluster-api-state-metrics to get a feeling how fast we can make progress in extending kube-state-metrics.

**Comment by chrischdi** [comment]
Some progress on the topic:

I invested some time in https://github.com/kubernetes/kube-state-metrics/issues/1755 which resulted in the PR https://github.com/kubernetes/kube-state-metrics/pull/1777 to start some feedback.

Running kube-state-metrics from the linked branch and using the config in https://github.com/kubernetes/kube-state-metrics/pull/1777#issuecomment-1174830715 would already cover nearly all metrics of the proposal, except the `labels` metrics which I did not yet take a look at.

As of now I only see one small disadvantage for using the configuration style kube-state-metrics: we may have to split the `paused` metric to `annotation_paused` and (if matches CR) `spec_paused` because the config (currently) does not provide the feature of combining values from different paths in the CR.

All in all I still think going forward with upstream kube-state-metrics makes way more sense then implementing a custom binary.

**Comment by chrischdi** [comment]
- https://github.com/kubernetes/kube-state-metrics/pull/1777 finally got merged today 🎉 

I will follow up the next days with a WIP PR which already integrates kube-state-metrics's helm chart into Tilt, similar to prometheus, grafana, ...

Local version is already running and seems to integrate greatly 🎉

**Comment by fabriziopandini** [comment]
@chrischdi can we close this issue now and move pending items to separated issues? (I have already opened https://github.com/kubernetes-sigs/cluster-api/issues/7158)

**Comment by chrischdi** [comment]
> @chrischdi can we close this issue now and move pending items to separated issues? (I have already opened #7158)

I've got two AI's I want to do and would have closed this issue afterwards:
- [ ] resync the proposal to the current state
- [ ] review again the `*status_*replica*` metrics for consistency purposes

Also the issue mentions the point ` clarify and implement release manifest`, I am also ok with not doing this for now and/or creating a separate issue for that.

**Comment by sbueringer** [comment]
I think the two sub-tasks that you mentioned + a separate issue for release manifests would be good.

I'm not sure if we want to release the manifests as long as we are writing / maintaining them manually. So this could depend on the gen tool.

**Comment by chrischdi** [comment]
> I'm not sure if we want to release the manifests as long as we are writing / maintaining them manually. So this could depend on the gen tool.

Fair point to get discussed in the follow-up issue then 👍 

Ok, I will do so and also create the issue.

**Comment by chrischdi** [comment]
Closing here by marking the last step as done 🎉  / via creation of:
- #7229 

/close
