### ISSUE TITLE
RuntimeHooks for Addon-Management implementation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6546]
Implementation umbrella issue for https://github.com/kubernetes-sigs/cluster-api/issues/6374
As the proposal (https://github.com/kubernetes-sigs/cluster-api/pull/6418) has been merged, we can start with the implementation now.

Done:
* [x] Add API types (#6537 @ykakarap @killianmuldoon )
* [x] Implement lifecycle hooks without tracking (@ykakarap) #6608
* [x] Implement lifecycle hooks with tracking (except delete) (@ykakarap) #6629
* [x] Verify that up/down conversion of embedded Cluster resources would work (https://github.com/sbueringer/cluster-api/pull/50)
* [x] Implement e2e test
    * PR initial test: (#6664 @killianmuldoon)
    * Follow-up: test blocking behavior (#6761 @killianmuldoon)
* [x] BeforeClusterDelete (#6644 @ykakarap)
* [x] book: documentation (#6756 @sbueringer)
* [x] Make sure that we test the BeforeClusterDelete hook in e2e (#6805 @killianmuldoon)

TODO before v1.2.0 release:

\-

Follow-up:
* Sequential upgrades (or not) and what does it mean for lifecycle hooks: #6651

/kind feature
/area runtime-sdk
