### ISSUE TITLE
UMBRELLA: Versioning and Support

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#730]
**Describe the solution you'd like**
Document where folks can find specific providers implementations. 
When we cut v1alpha1 the first questions are going to be "what is supported", and "where do I find them?

On a separate note it would be ideal if this was somehow automated via some publishing mechanism. 

/kind feature
/kind documentation

**Comment by frapposelli** [comment]
/cc @frapposelli @sflxn 

this is of interest for CAPV as well

**Comment by timothysc** [comment]
Here is a broad-strokes overview of the expectation here: 

problem statement -> requirements -> options -> recommendations -> plan = KEP-ish

**Comment by vincepri** [comment]
Adding a plan of action for next steps:

- [ ] Proposal in google doc form with problem statement, objective and implementation (solution) details
- [ ] Discuss the proposal in the next community meeting and get buy-in on it
- [ ] Implement release process documenting required steps (gitbook?)
- [ ] [bonus] Automating the release process (probably post v1alpha1)

**Comment by chuckha** [comment]
Some ideas about [versioning in this document](https://docs.google.com/document/d/1BrBDnMYERC7-mgweMtxx7ejJhAE5aCc3TS2_HJqDv3c/edit#heading=h.s3pbua1p48bk). Must be a member of kubernetes-dev or sig-cluster-lifecycle google groups.

**Comment by neolit123** [comment]
cc

**Comment by neolit123** [comment]
added some comments, for me key points are:
- standardize/interface kubeadm as the default boostrapper, move such logic outside of providers, but allow them the flex. this is already quite fragmented.
- standardize the support matrix template for providers in documentation (MD templates) and machine consumable way per provider repo or in the CAPI repo.
- consider complex version schemas such as "provider-version-capi-version".

**Comment by chuckha** [comment]
- [ ] [Document existing release process](https://github.com/kubernetes-sigs/cluster-api/issues/764)

**Comment by ncdc** [comment]
@chuckha what are our "done" criteria for this issue - when can we close the issue?

**Comment by chuckha** [comment]
@ncdc I think the lowest bar for closing this would be to open an issue on each provider telling them to document the version of kubernetes that is supported by which version of the provider.

A support grid on the provider.

**Comment by ncdc** [comment]
If that's the required action, can we close this now and proceed to open 1 issue per provider?

**Comment by chuckha** [comment]
yes, that's fine.

I'd recommend a grid similar to the one found in client-go. It would also be good to document the version of cluster-api that the version of the provider depends on, but I suppose not entirely necessary

**Comment by ncdc** [comment]
I think it is necessary to document the cluster-api version, since a full deployment requires both the cluster-api controllers and the provider controllers, and they have to talk the same language.

**Comment by ncdc** [comment]
Ok, before we close this, perhaps let's discuss the grid(s). Would you want something like this?

||Cluster API 0.1|Cluster API 0.2|
|-|-|-|
|AWS Provider 0.1|✓||
|AWS Provider 0.2||✓|

||Kubernetes 1.11|Kubernetes 1.12|Kubernetes 1.13|Kubernetes 1.14|
|-|-|-|-|-|
|AWS Provider 0.1|✓|✓|✓|
|AWS Provider 0.2||✓|✓|✓|

**Comment by chuckha** [comment]
Too bad READMEs don't do 3 dimensional grids 😂 

That looks great to me :) Thanks for putting that together!

**Comment by ncdc** [comment]
AWS: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/628

**Comment by ncdc** [comment]
@chuckha I think I got all the ones in `kubernetes-sigs`. Should I do the others too (OpenShift, Baidu, Tencent Cloud)?

**Comment by chuckha** [comment]
I think that's fine. I'm not sure how people are starting cluster-api-provider repos these days, but wherever those instructions live we should add this chart to the getting-started guide. I'll open a separate issue for that.

Thanks a bunch @ncdc !

/close

**Comment by detiber** [comment]
@chuckha The gitbook would probably be the best place for that.
