### ISSUE TITLE
Setup initial release docs, dates and team

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7389]
This is an umbrella issue which captures tasks we want to do **before** the v1.4.0 release cycle starts to have a starting point from which we can iterate.

## Preparation tasks

* [x] Assemble the release team for v1.4 (@CecileRobertMichon)
  * [x] PR to add the release team to the doc: #7470
* [x] Finalize v1.3 + v1.4 release dates + initial release cycle definition (@sbueringer #7391)
* [x] #7476 (@ykakarap)
  * Initial setup done, adding Joe now
* [x] #7499 (@sbueringer)
* [ ] Write doc for Kubernetes bump: #7561 (@sbueringer)

/kind feature

**Comment by sbueringer** [comment]
cc @ykakarap @CecileRobertMichon I added a point about organization / GitHub teams / Slack aliases / ...

**Comment by ykakarap** [comment]
@sbueringer Issue for setting up the github and slack teams: https://github.com/kubernetes-sigs/cluster-api/issues/7476

(I dont have edit permissions on the issue to add it to the issue description.)

**Comment by sbueringer** [comment]
Thx, added.

**Comment by sbueringer** [comment]
@ykakarap I would move "Figure out how to coordinate / sync / work / ... together" out of this issue feel free to handle it as appropriate with the new release team.

I would close out this issue when the release tasks PR and the upcoming Kubernetes bump PR are merged.
