### ISSUE TITLE
Tasks for v1.3 release cycle

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7527]
**Note** We're roughly testing the new workflow for the current release cycle. I doesn't fit 100% of course without a release team.

Please see the corresponding section in [release-tasks.md](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md) for documentation of individual tasks.

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.
* The following is based on the v1.4 release cycle. Modify according to the tracked release cycle.

Week -3 to 1:
* [x] [Release Lead] [Set a tentative release date for the minor release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#set-a-tentative-release-date-for-the-minor-release)
* [x] [Release Lead] [Assemble release team](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#assemble-release-team) [doesn't apply]

Week 1:
* [x] [Release Lead] [Finalize release schedule and team](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#finalize-release-schedule-and-team) [release team doesn't apply]
* [x] [Release Lead] [Prepare main branch for development of the new release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
  * PR: #6833
* [x] [Communications Manager] [Add docs to collect release notes for users and migration notes for provider implementers](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers) [release note doc doesn't apply]
  * PR: #6698 
* [x] [Communications Manager] [Update supported versions](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#update-supported-versions)
  * PR: #6850

Week 1 to 4:
* [x] [Release Lead] [Track] [Remove previously deprecated code](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#track-remove-previously-deprecated-code)
  * PR: #6779

Week 5:
* [x] [Release Lead] [Cut the v1.2.1 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 9:
* [x] [Release Lead] [Cut the v1.2.2 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 11 to 12:
* [x] [Release Lead] [Track] [Bump dependencies](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#track-bump-dependencies)

Week 13:
* [x] [Release Lead] [Cut the v1.2.3 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 14:
* [x] [Release Lead] [Cut the v1.2.4 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 16:
* [x] [Release Lead] [Cut the v1.3.0-beta.0 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Create a new GitHub milestone for the next release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#create-a-new-github-milestone-for-the-next-release)

Week 17:
* [x] [Release Lead] [Cut the v1.3.0-beta.1 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.2.5 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Select release lead for the next release cycle

Week 18:
* [x] [Release Lead] [Create the release-1.3 release branch](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#create-a-release-branch)
  * PR: https://github.com/kubernetes/test-infra/pull/28009
* [x] [Release Lead] [Cut the v1.3.0-rc.0 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [CI Manager] [Setup jobs and dashboards for the release-1.3 release branch](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch)
  * PR: https://github.com/kubernetes/test-infra/pull/28010
* [x] [Communications Manager] [Ensure the book for the new release is available](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#ensure-the-book-for-the-new-release-is-available)
  * PR: https://github.com/kubernetes/k8s.io/pull/4466
  * PR: #7545

Week 18 to 20:
* [x] [Communications Manager] [Polish release notes](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#polish-release-notes)

Week 19:
* [x] [Release Lead] [Cut the v1.3.0-rc.1 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 20:
* [x] [Release Lead] [Cut the v1.3.0 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.2.6 release](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Organize release retrospective [doesn't apply]
* [x] [Communications Manager] [Change production branch in Netlify to the new release branch](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#change-production-branch-in-netlify-to-the-new-release-branch)
* [x] [Communications Manager] [Update clusterctl links in the quickstart](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#update-clusterctl-links-in-the-quickstart)
  * PR: #7595

Continuously:
* [Release lead] [Maintain the GitHub release milestone](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#continuously-maintain-the-github-release-milestone)
* [Communications Manager] [Communicate key dates to the community](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#continuously-communicate-key-dates-to-the-community)
* [Communications Manager] Improve release process documentation
* [Communications Manager] Maintain and improve user facing documentation about releases, release policy and release calendar
* [CI Manager] [Monitor CI signal](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#continuously-monitor-ci-signal)
* [CI Manager] [Reduce the amount of flaky tests](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)
* [CI Manager] [Bug triage](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#continuously-bug-triage)
* [CI Manager] Maintain and improve release automation, tooling & related developer docs

If and when necessary:
* [x] [Release Lead] [Track] [Bump the Cluster API apiVersion](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#optional-track-bump-the-cluster-api-apiversion) [doesn't apply]
* [x] [Release Lead] [Track] [Bump the Kubernetes version](https://github.com/sbueringer/cluster-api/blob/pr-release-tasks/docs/release/release-tasks.md#optional-track-bump-the-kubernetes-version)

**Comment by sbueringer** [comment]
cc @ykakarap (fyi)

**Comment by sbueringer** [comment]
Done 🎉 

/close
