### ISSUE TITLE
Tasks to bump to Kubernetes v1.26

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7671]
This issue is tracking the tasks that should be implemented **after** the Kubernetes minor release has been released.

## Tasks

Prerequisites:
* [x] Decide which Cluster API release series will support the new Kubernetes version
  * If feasible we usually cherry-pick the changes back to the latest release series.
  * The v1.26 Kubernetes version support should go back till v1.2.

### Supporting managing and running on the new Kubernetes version

This section contains tasks to update our book, e2e testing and CI to use and test the new Kubernetes version 
as well as changes to Cluster API that we might have to make to support the new Kubernetes version. All of these 
changes should be cherry-picked to all release series that will support the new Kubernetes version.

* [x] Modify quickstart and CAPD to use the new Kubernetes release:
    * Bump the Kubernetes version in:
        * `test/*`: search for occurrences of the previous Kubernetes version
        * `Tiltfile`
    * Ensure the latest available kind version is used (including the latest images for this kind release)
    * Verify the quickstart manually
    * Prior art: #7156
    * PR: https://github.com/kubernetes-sigs/cluster-api/pull/7799
    * PR 1.3: #7859
    * PR 1.2: #7860
* [x] Job configurations:
    * For all releases which will support the new Kubernetes version:
        * Update `INIT_WITH_KUBERNETES_VERSION`.
        * Add new periodic upgrade jobs .
        * Adjust presubmit jobs so that we have the latest upgrade jobs available on PRs.
    * Prior art: https://github.com/kubernetes/test-infra/pull/27421
    * PR: https://github.com/kubernetes/test-infra/pull/28309
* [x] Update book:
    * Update supported versions in `versions.md`
    * Update job documentation in `jobs.md`
    * Prior art: #7194 #7196
    * PRs: https://github.com/kubernetes-sigs/cluster-api/pull/7801 https://github.com/kubernetes-sigs/cluster-api/pull/7802
    * PRs 1.3: #7861
    * PRs 1.2: #7862
* [x] Issues specific to the Kubernetes minor release:
    * Sometimes there are adjustments that we have to make in Cluster API to be able to support
      a new Kubernetes minor version. Please add these issues here when they are identified.

### Using new Kubernetes dependencies

This section contains tasks to update Cluster API to use the latest Kubernetes Go dependencies and related topics 
like using the right Go version and build images. These changes are only made on the main branch. We don't
need them in older releases as they are not necessary to manage workload clusters of the new Kubernetes version or
run the Cluster API controllers on the new Kubernetes version.

* [x] Ensure there is a new controller-runtime minor release which uses the new Kubernetes Go dependencies.
    * CR release v0.14.1 is using v1.26 dependencies
* [x] Update our Prow jobs for the `main` branch to use the correct `kubekins-e2e` image
    * It is recommended to have one PR for presubmit and one for periodic jobs to reduce the risk of breaking the periodic jobs.
    * Prior art: presubmit jobs: https://github.com/kubernetes/test-infra/pull/27311
    * Prior art: periodic jobs: https://github.com/kubernetes/test-infra/pull/27311
    * PR: presubmit jobs: https://github.com/kubernetes/test-infra/pull/28337
    * PR: periodic jobs: https://github.com/kubernetes/test-infra/pull/28338
* [x] [does not apply] Bump the Go version in Cluster API: (if Kubernetes is using a new Go minor version)
    * Search for the currently used Go version across the repository and update it
    * We have to at least modify it in: `.github/workflows`, `hack/ensure-go.sh`, `.golangci.yml`, `cloudbuild*.yaml`, `go.mod`, `Makefile`, `netlify.toml`, `Tiltfile`
    * Prior art: #7135
* [x] Bump controller-runtime: #7906
* [x] Bump controller-tools: #7907
* [x] Bump the Kubernetes version used in integration tests via `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile`
    * **Note**: This PR should be cherry-picked as well. It is part of this section as it depends on kubebuilder/controller-runtime
      releases and is not strictly necessary for [Supporting managing and running on the new Kubernetes version](#supporting-managing-and-running-on-the-new-kubernetes-version).
    * Prior art: #7193
    * PR: #7835
    * PR 1.3: #7863
    * PR 1.2: #7864
* [x] Bump conversion-gen via `CONVERSION_GEN_VER` in `Makefile`
    * Prior art: #7118
    * PR: #7847
* [x] Inform users about klog flags removal when importing Kubernetes v1.26
    * Issue: https://github.com/kubernetes-sigs/cluster-api/issues/6069

**Comment by fabriziopandini** [comment]
FYI [this issue](https://github.com/kubernetes-sigs/cluster-api/issues/6069) seems linked to this work

**Comment by sbueringer** [comment]
> FYI [this issue](https://github.com/kubernetes-sigs/cluster-api/issues/6069) seems linked to this work

Yup thx it is. @ykakarap can you please add it as release related task to the 2nd section?

**Comment by ykakarap** [comment]
> > FYI [this issue](https://github.com/kubernetes-sigs/cluster-api/issues/6069) seems linked to this work
> 
> Yup thx it is. @ykakarap can you please add it as release related task to the 2nd section? (Using new Kubernetes dependencies)

done

**Comment by aniruddha2000** [comment]
/assign

I would like to work on this 😊

**Comment by sbueringer** [comment]
Quick update. I discussed with Fabrizio if we should support v1.26 in v1.2.

Given:
> For a given Cluster API minor release, we give best-effort support for future Kubernetes versions that are released 
> during the release's active support period. Depending on the changes made in Kubernetes, users may be required to
> update to the next patch release of Cluster API to maintain compatibility.

We would support v1.26 in v1.2. We are interpreting "best-effort" as we are trying to support it except if we find a major showstopper while implementing it.

Independent of that I'll bring up the discussion if we want to support new Kubernetes releases in non-recent stable releases in the future. But this won't affect the Kubernetes 1.26 bump.

**Comment by aniruddha2000** [comment]
Is there any reference I can look to find the go minor version Kubernetes is using?
I can see [go.mod](https://github.com/kubernetes/kubernetes/blob/master/go.mod#L9) is using 1.19.

**Comment by sbueringer** [comment]
> Is there any reference I can look to find the go minor version Kubernetes is using? I can see [go.mod](https://github.com/kubernetes/kubernetes/blob/master/go.mod#L9) is using 1.19.

I usually refer to the release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md

Not sure why the latest entry there is 1.19.4. The 1.26 kubekins image is using v1.19.4. But given that we only need to know the minor version it's good enough.

So tl;dr we don't have to bump further as we are already using 1.19

**Comment by aniruddha2000** [comment]
What would be the conversion-gen version for this release? In the [release tag I](https://github.com/kubernetes/code-generator/tags) can see `v0.26.0`.

@sbueringer can you describe what kind of work I have to do here?
```
PR 1.3: TODO
PR 1.2: TODO
```

**Comment by sbueringer** [comment]
> What would be the `conversion-gen` version for this release? In the [release tag I](https://github.com/kubernetes/code-generator/tags) can see `v0.26.0`.

v0.26.0 is perfect

> @sbueringer can you describe what kind of work I have to do here?
> 
> ```
> PR 1.3: TODO
> PR 1.2: TODO
> ```

Let's start with the ones below "Modify quickstart and CAPD to use the new Kubernetes release". Essentially open PRs against release-1.3 and release-1.2 with a cherry-pick of the commit from https://github.com/kubernetes-sigs/cluster-api/pull/7799

We always try to do this with the bot but because of conflicts that's not always possible (https://github.com/kubernetes-sigs/cluster-api/pull/7799#issuecomment-1369425929)

I would say start with opening a PR against release-1.3 and try to best-effort resolve the conflicts the way you think it's correct. I'll take a closer look once the PR is open and let you if there is more to do.

**Comment by sbueringer** [comment]
@aniruddha2000 Do you have time to work on those cherry-picks and on the findings on https://github.com/kubernetes/test-infra/pull/28309? Otherwise I"m happy to take this over. I just want to reduce the time that our branches are in different states.

**Comment by aniruddha2000** [comment]
@sbueringer Yes I will open the cherry picks by today and will resolve the findings

One query for the cherry-pick is `Should I open PR with the same changes targeting the branch 'release-1.2' & 'release-1.3'?` Because it's my first time performing something like this.

**Comment by sbueringer** [comment]
> One query for the cherry-pick is Should I open PR with the same changes targeting the branch 'release-1.2' & 'release-1.3'? Because it's my first time performing something like this.

No worries, feel free to ask as many questions as you want :)

>  Should I open PR with the same changes targeting the branch 'release-1.2' & 'release-1.3'? 

Yes

That's what I tried to say here:

> https://github.com/kubernetes-sigs/cluster-api/issues/7671#issuecomment-1371101872

**Comment by sbueringer** [comment]
Quick update about the current state / merge order. Next steps:
* [Tomorrow] v1.3.x and v1.2.x Patch releases
* v1.26 implementation
  * #7859
  * #7860
* Corresponding test job changes
  * https://github.com/kubernetes/test-infra/pull/28309
* Finally corresonding doc changes
  * Versions:
    * https://github.com/kubernetes-sigs/cluster-api/pull/7801
    * #7861
    * #7862
  * Job documentation:
    * #7802

I'll start merging the PRs (when they are ready) after the patch releases

(cc @aniruddha2000 @ykakarap @fabriziopandini)

**Comment by sbueringer** [comment]
Okay all of them are merged now.

Kudos again to @aniruddha2000 !


Next up would be bumping controller-runtime and controller-tools (only on main)

@aniruddha2000 Do you want to take care of this as well?

**Comment by aniruddha2000** [comment]
Yes, @sbueringer I can. But are there any specific places where I have to make the changes? or it's the project-level controller-runtime & controller-tools in the go.mod file?

**Comment by sbueringer** [comment]
controller-tools is bumped in the Makefile
prior art: https://github.com/kubernetes-sigs/cluster-api/pull/7262/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
(makefile + run `make generate-modules generate-manifests`)

**Comment by sbueringer** [comment]
Controller-runtime should be bumped in all of our go.mod files + documented in the migration doc

**Comment by sbueringer** [comment]
Perfect. We're almost done.

One last task: `Inform users about klog flags removal when importing Kubernetes v1.26`

I'll take a closer look at that one later. I think it just comes down to making sure our next release notes contain a note (I just want to verify something to make sure we add the right note)

**Comment by ykakarap** [comment]
All the items in the list are complete! Bumping to support Kubernetes v1.26 is now complete.

Big thanks to everyone who helped with this effort! 👏🏼 

/close

**Comment by ykakarap** [comment]
> Perfect. We're almost done.
> 
> One last task: `Inform users about klog flags removal when importing Kubernetes v1.26`
> 
> I'll take a closer look at that one later. I think it just comes down to making sure our next release notes contain a note (I just want to verify something to make sure we add the right note)

This is now tracked in the [release tracking issue](https://github.com/kubernetes-sigs/cluster-api/issues/7672).
