### ISSUE TITLE
Tasks for v1.4 release cycle

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7672]
Please see the corresponding section in [release-tasks.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.

Week -3 to 1:
* [x] [Release Lead] [Set a tentative release date for the minor release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#set-a-tentative-release-date-for-the-minor-release)
* [x] [Release Lead] [Assemble release team](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#assemble-release-team)

Week 1:
* [x] [Release Lead] [Finalize release schedule and team](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#finalize-release-schedule-and-team)
* [x] [Release Lead] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/7692
* [x] [Communications Manager] [Add docs to collect release notes for users and migration notes for provider implementers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers)
   * Migration doc: https://github.com/kubernetes-sigs/cluster-api/pull/7698
* [x] [Communications Manager] [Update supported versions](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions)
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/7696

Week 1 to 4:
* [x] [Release Lead] [Track] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-remove-previously-deprecated-code)
   * Issue: https://github.com/kubernetes-sigs/cluster-api/issues/7713

Week 6:
* [x] [Release Lead] [Cut the v1.2.x and v1.3.x releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 9:
* [x] [Release Lead] [Cut the v1.2.x and v1.3.x releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 11 to 12:
* [x] [Release Lead] [Track] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-bump-dependencies)
   * Note: This will probably be taken care by dependabot automation (controller-runtime will need a manual bump).

Week 13:
* [x] [Release Lead] [Cut the v1.4.0-beta.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.2.x and v1.3.x releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Create a new GitHub milestone for the next release (v1.5) ](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-new-github-milestone-for-the-next-release)
   * [x] Once the milestone is available announce that we should the issues in the current milestone and move to the next as needed.

Week 14:
* [x] [Release Lead] [Cut the v1.4.0-beta.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Select release lead for the next release cycle

Week 15 (**Code Freeze**):
* [x] [Release Lead] [Create the release-1.4 release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-release-branch)
* [x] [Release Lead] [Cut the v1.4.0-rc.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [CI Manager] [Setup jobs and dashboards for the release-1.4 release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch)
* [x] [Communications Manager] [Ensure the book for the new release is available](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#ensure-the-book-for-the-new-release-is-available)

Week 15 to 17:
* [x] [Communications Manager] [Polish release notes](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#polish-release-notes)

Week 16:
* [x] [Release Lead] [Cut the v1.4.0-rc.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 17:
* [x] [Release Lead] [Cut the v1.4.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.2.x and v1.3.x releases](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Organize release retrospective
* [x] [Communications Manager] [Change production branch in Netlify to the new release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#change-production-branch-in-netlify-to-the-new-release-branch)
    * Note: Only few people have access to Netlify right now. Ping them to get this done.
* [x] [Communications Manager] [Update clusterctl links in the quickstart](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-clusterctl-links-in-the-quickstart)

Continuously:
* [Release lead] [Maintain the GitHub release milestone](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-maintain-the-github-release-milestone)
* [Communications Manager] [Communicate key dates to the community](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-communicate-key-dates-to-the-community)
* [Communications Manager] Improve release process documentation
* [Communications Manager] Maintain and improve user facing documentation about releases, release policy and release calendar
* [CI Manager] [Monitor CI signal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-monitor-ci-signal)
* [CI Manager] [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)
* [CI Manager] [Bug triage](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bug-triage)
* [CI Manager] Maintain and improve release automation, tooling & related developer docs

If and when necessary:
* [ ] [Release Lead] [Track] [Bump the Cluster API apiVersion](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-bump-the-cluster-api-apiversion)
* [ ] [Release Lead] [Track] [Bump the Kubernetes version](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-bump-the-kubernetes-version)
   * Issue: https://github.com/kubernetes-sigs/cluster-api/issues/7671
* [ ] [Communications Manager] Add a user facing doc for cluster api
   * [ ] Add a point that users can now drop klog flags. Ref: https://github.com/kubernetes-sigs/cluster-api/pull/7955#discussion_r1081689610

**Comment by ykakarap** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Comment by fabriziopandini** [comment]
/triage accepted
it is awesome to see this work kicking off...

**Comment by oscr** [comment]
@ykakarap Maybe it would be useful to have 1.4 release specific label(s) on the issues related to this release? I'm thinking it might be nice to be able to quickly find any and all release specific issues.

**Comment by fabriziopandini** [comment]
can we use milestone?

**Comment by furkatgofurov7** [comment]
+1 for using release milestone

**Comment by cpanato** [comment]
+1 as well

**Comment by sbueringer** [comment]
@oscr I think the goal of [[Add docs to collect release notes for users and migration notes for provider implementers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers)](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers) was to add one doc for provider changes and one doc to track user facing changes.

As far as I can tell the PR only added the doc for providers.

**Comment by oscr** [comment]
@sbueringer I must have missed this. It will be fixed. Thank you for pointing it out.

**Comment by hackeramitkumar** [comment]
@ykakarap  Should I open a PR for removing previously deprecated code??

**Comment by hackeramitkumar** [comment]
> @kubernetes-sigs/cluster-api-release-team Should I open a PR for removing previously deprecated code??

@fabriziopandini

**Comment by ykakarap** [comment]
Just trying to track what needs to go into the user facing changes doc. Looks like we have at least one item: https://github.com/kubernetes-sigs/cluster-api/pull/7955#discussion_r1081689610. Do we have a list of any other items that need to go into this doc?

**Comment by furkatgofurov7** [comment]
> [ ] [CI Manager] [Setup jobs and dashboards for the release-1.4 release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch)

cc @ykakarap ^ is:
- tracked separately in https://github.com/kubernetes-sigs/cluster-api/issues/8270
- will be completed in https://github.com/kubernetes/test-infra/pull/29006

**Comment by sbueringer** [comment]
Fyi I created the release branch together with Killian.

From now on we have to cherry-pick PRs if they should make it into 1.4.x

**Comment by ykakarap** [comment]
The release retrospective was organized on March 30th. 
Recording link: https://www.youtube.com/watch?v=4-6XJJ1ACdw (also linked in the release team meeting notes)

With this the v1.4.0 release cycle is complete. 

Closing the issue.

/close
