### ISSUE TITLE
Tracking issue for dropping code deprecated in v1.3 release

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7713]
The following parts of the code base were deprecated in the previous release (v1.3). This is a tracking issue for all the work that needs to be done to drop all the deprecated work:

- [x] Drop [`MachineHealthCheckSuccededCondition`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/api/v1beta1/condition_consts.go#L143) in `api/v1beta1/condition_consts.go` (@knabben)
   - Drop the constant and make sure to replace all uses, if any, with `MachineHealthCheckSucceededCondition`
   - Update the in book.
- [x] Drop `clusterctl backup` command (@oscr)
   - This command was deprecated in favor of `clusterctl move --to-directory`.
   - Drop the file `cmd/clusterctl/cmd/backup.go`
   - Drop the [`Backup(options BackupOptions) error`](https://github.com/ykakarap/cluster-api/blob/4ee2872d4757bff19f31136129dbcf8b1b22d8a8/cmd/clusterctl/client/client.go#L60) method from the `Client` interface and the implementations of this interface: `clusterctlClient` and `fakeClient`
   - Drop [`BackupOptions`](https://github.com/ykakarap/cluster-api/blob/4ee2872d4757bff19f31136129dbcf8b1b22d8a8/cmd/clusterctl/client/move.go#L51-L65) from `cmd/clusterctl/client/move.go`
   - Drop [`Backup(namespace string, directory string) error`](https://github.com/ykakarap/cluster-api/blob/4ee2872d4757bff19f31136129dbcf8b1b22d8a8/cmd/clusterctl/client/cluster/mover.go#L56-L59) method from the `ObjectMover` interface and the implementations of this interface: `objectMover` and `fakeObjectMover`
   - Update in book.
- [x] Drop `clusterctl restore` command (@hackeramitkumar )
   - This command was deprecated in favor of `clusterctl move --from-directory`.
   - Drop the file `cmd/clusterctl/cmd/restore.go`
   - Drop the [`Restore(options RestoreOptions) error`](https://github.com/ykakarap/cluster-api/blob/4ee2872d4757bff19f31136129dbcf8b1b22d8a8/cmd/clusterctl/client/client.go#L65) method from the `Client` interface and the implementations of this interface: `clusterctlClient` and `fakeClient`
   - Drop [`RestoreOptions`](https://github.com/ykakarap/cluster-api/blob/4ee2872d4757bff19f31136129dbcf8b1b22d8a8/cmd/clusterctl/client/move.go#L67-L77) from `cmd/clusterctl/client/move.go`
   - Drop [`Restore(namespace string, directory string) error`](https://github.com/ykakarap/cluster-api/blob/4ee2872d4757bff19f31136129dbcf8b1b22d8a8/cmd/clusterctl/client/cluster/mover.go#L61-L64) method from the `ObjectMover` interface and the implementations of this interface: `objectMover` and `fakeObjectMover`
   - Update in book.
- [x] Drop the [`--disable-no-echo`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/cmd/clusterctl/cmd/describe_cluster.go#L131-L132) flag in `clusterctl describe` command. (@knabben)
   - Drop the corresponding variable (`disableNoEcho `) and its uses from the file.
   - Update in book.
- [x] Drop the [`--list-images`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/cmd/clusterctl/cmd/init.go#L118) flag in `clusterctl init` command. (@knabben)
   - Drop the corresponding variable `listImages`  and its uses from the file.
   - Update in book.
- [x] Drop [`CloneTemplate`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/controllers/external/util.go#L91-L119) and  [`CloneTemplateInput`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/controllers/external/util.go#L62-L89) (@knabben)
   - Replace its uses, if any, with [`CreateFromTemplate`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/controllers/external/util.go#L148-L174) and [`CreateFromTemplateInput`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/controllers/external/util.go#L121-L146)
   - Update in book.
- [x] Drop [`NewServer`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/exp/runtime/server/server.go#L73-L78) in `exp/runtime/server/server.go` (@knabben)
   - Replace its uses, if any, with [`New`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/exp/runtime/server/server.go#L80-L107)
   - Update in book.
- [x] Drop [`ClusterTopologyManagedFieldsAnnotation`](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/api/v1beta1/common_types.go#L46) (@knabben)
   - Drop all of this uses.
   - Update in book.

**Comment by oscr** [comment]
@ykakarap I suggest making each item it's own ticket and using this ticket as an overview. Then each ticket can be discussed and assigned separately, to avoid having multiple people working on the same task. I also suggest each item should include updating the docs :)

**Comment by chiukapoor** [comment]
Hello Team, I will work on the task to `Drop clusterctl restore command`

**Comment by oscr** [comment]
@chiukapoor Great to hear! I suspect you should be able to look at #7752 for inspiration. Note the apidiff test will fail for your pr and this is expected.

**Comment by chiukapoor** [comment]
Sure @oscr, will refer to https://github.com/kubernetes-sigs/cluster-api/pull/7752 :)

/assign

**Comment by hackeramitkumar** [comment]
I will work on the task to `Drop [CloneTemplate](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/controllers/external/util.go#L91-L119) and [CloneTemplateInput](https://github.com/ykakarap/cluster-api/blob/5f5946ea4f1a350d48068e15f9a7b49afcff5a99/controllers/external/util.go#L62-L89)`

**Comment by sbueringer** [comment]
@ykakarap Just a note. For some of the sub-tasks we have to update .golangci.yaml can you add that to the respective sub-tasks? (e.g. https://github.com/kubernetes-sigs/cluster-api/blob/de575caffa265191feebd44c6e0fc7eb54d56c11/.golangci.yml#L222-L225)

**Comment by knabben** [comment]
hey, I will get the first `Drop MachineHealthCheckSuccededCondition in api/v1beta1/condition_consts.go`.

**Comment by sbueringer** [comment]
Quick update: after recent PRs that now only leaves the removel of `clusterctl restore`

**Comment by ykakarap** [comment]
Looks like @chiukapoor Is already assigned to that item.  Once that is done I will close this issue.

**Comment by hackeramitkumar** [comment]
@chiukapoor are you working on 'clusterctl restore' task?? If not then I can take it.

**Comment by chiukapoor** [comment]
Hey @hackeramitkumar, I have started the work will push changes in couple of days.

**Comment by hackeramitkumar** [comment]
@chiukapoor , thank you

> Hey @hackeramitkumar, I have started the work will push changes in couple of days.

**Comment by hackeramitkumar** [comment]
@chiukapoor are you still working on ` cluster restore ` task? Actually we have to done it before the next patch release.

**Comment by sbueringer** [comment]
> @chiukapoor are you still working on `cluster restore` task? Actually we have to done it before the next patch release.

We don't have to do it before the next patch release as the change will be done on main and the next release "from main" will be the first beta.

**Comment by ykakarap** [comment]
Echoing what @sbueringer said, this does not block the next v1.3 and v1.2 patch releases.

It would just be nice to get done to close the deprecation work on main. 🙂

**Comment by sbueringer** [comment]
Thx @hackeramitkumar for taking this over.

Thx everyone!

/close

**Comment by ykakarap** [comment]
Thank you everyone who worked on this issue! 🙏🏼

**Comment by fabriziopandini** [comment]
dream team!
