### ISSUE TITLE
Umbrella issue for `Label Sync Between Machines and underlying Kubernetes Nodes` proposal implementation

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7730]
This is an umbrella issue for the implementation of the [**Label Sync Between Machines and underlying Kubernetes Nodes**](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220927-label-sync-between-machine-and-nodes.md) proposal. As the proposal is merged the implementation can now be done.

The work is broken down into:

- [x]  Synchronization of CAPI Labels https://github.com/kubernetes-sigs/cluster-api/pull/7173
    - Notes:
        - A subset of labels as defined in [**Label domains & prefixes**](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220927-label-sync-between-machine-and-nodes.md#label-domains--prefixes) should be synced between the machine and the nodes.
        - SSA should be used to apply the labels the labels. Take special look at the labels that could be applied by kubeadm and could also be applied by the Machine Controller. This might lead to co-ownership. Making deletion harder.
- [x] Migrate machine controller tests to envtest and drop `disableNodeLabelSync`.
   - Issue: https://github.com/kubernetes-sigs/cluster-api/issues/7964
- [x]  Apply `node.cluster.x-k8s.io=uninitialized:NoSchedule` taint on newly created nodes which did have the labels synced. The taint should be removed after the labels are synced for the first time.
   - PR: https://github.com/kubernetes-sigs/cluster-api/pull/7993
- [x] Document optional Bootstrap provider contract to support `node.cluster.x-k8s.io=uninitialized:NoSchedule` at creation.

---
Issues/PRs that could be affected by this work:
- https://github.com/kubernetes-sigs/cluster-api/pull/7631

**Comment by sbueringer** [comment]
cc @srm09 (IIRC once this issue is completed there might be some work todo in CAPV)

**Comment by sbueringer** [comment]
@ykakarap is this issue done?

**Comment by ykakarap** [comment]
Yes. All the items are done. This issue can be closed.

/close

**Comment by lubronzhan** [comment]
Hi @ykakarap this new label will breaks existing cloud-providers for example cloud-provider-vsphere. Since it only tolerates existing k8s tolerations, https://github.com/kubernetes/cloud-provider-vsphere/blob/master/releases/v1.26/vsphere-cloud-controller-manager.yaml#L218-L230

CPI is crucial to initialize the node, setting provideID and externalIP on the node. Now node will stuck in uninitialized state, because CPI can't be deployed. And CAPI can't find the providerID of the node since CPI is not deployed. While CAPI won't remove the tolerations `node.cluster.x-k8s.io=uninitialized:NoSchedule` since it can't find the providerID.

This is a breaking change that either requires all cloud-providers to adopt this tolerations.

**Comment by fabriziopandini** [comment]
this is being discussed in https://github.com/kubernetes-sigs/cluster-api/issues/8357, fix in flight
