### ISSUE TITLE
Umbrella issue for `In place propagation of changes affecting Kubernetes objects only` proposal implementation

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7731]
This is an umbrella issue for the implementation of the [**In place propagation of changes affecting Kubernetes objects only**](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20221003-In-place-propagation-of-Kubernetes-objects-only-changes.md) proposal. As the proposal is merged the implementation can now be done.

The work is broken down into:

- [x]  Propagate labels from Managed Clusters and ClusterClass to the underlying KCP and MachineDeployment objects. 
    - PR: https://github.com/kubernetes-sigs/cluster-api/pull/7917
    - Other Issues/PRs that depend/affect this work:
       -  https://github.com/kubernetes-sigs/cluster-api/issues/7293
- [x]  Labels and Annotations should be always synced. Not only at create.
    - [x]  Cluster/ClusterClass to KCP
    - [x]  Cluster/ClusterClass to MachineDeployments
    - [x]  KCP to Machines, InfraMachines and KubeadmConfigs https://github.com/kubernetes-sigs/cluster-api/pull/8057
    - [x]  MachineDeployments to MachineSets https://github.com/kubernetes-sigs/cluster-api/pull/8110
    - [x] MachineSets to Machines https://github.com/kubernetes-sigs/cluster-api/pull/8111
    - [x] MachineSets to InfraMachines and BootstrapConfigs https://github.com/kubernetes-sigs/cluster-api/pull/8060
- In-place propagation
    
    Fields like labels, annotations, `MinReadySeconds`, `NodeDrainTimeout`, `NodeVolumeDetachTimeout`, `NodeDeletionTimeout` , things that only affect the Kubernetes objects and not the underlying node should not trigger a rollout and be propagated in-place.
    
    - [x] MachineDeployment to MachineSet
       - PR: https://github.com/kubernetes-sigs/cluster-api/pull/8110
    - [x] MachineSets to Machines
       - PR: https://github.com/kubernetes-sigs/cluster-api/pull/8111
    - [x] KCP to Machines
        - PR: https://github.com/kubernetes-sigs/cluster-api/pull/8057

**Follow-up**:
- [x] End-to-end testing https://github.com/kubernetes-sigs/cluster-api/pull/8171 
- [x] Add support for `rolloutAfter` in MachineDeployments. https://github.com/kubernetes-sigs/cluster-api/pull/8216
   - `clusterctl alpha rollout restart md/md-0` should switch to using `rolloutAfter`
- [x] Documentation Updates
   - PR: https://github.com/kubernetes-sigs/cluster-api/pull/8319 

**Follow-up (can do after v1.4)**:
- [ ] Revision history support for in-place mutating changes in MDs.
   - Issue: https://github.com/kubernetes-sigs/cluster-api/issues/8392 
- [ ] Drop `disableInPlacePropagation` from KCP reconciler and migrate the affected tests to envtest. 
   - Issue: https://github.com/kubernetes-sigs/cluster-api/issues/8393
- [ ] Clean up `FindOldMachineSets` to drop the first return parameter. It is never used. 
   - Issue: https://github.com/kubernetes-sigs/cluster-api/issues/8394
   - Ref: https://github.com/kubernetes-sigs/cluster-api/pull/7921#discussion_r1105855474
- [ ] Replace all occurrences of `helperOptions` with `ssa.FilterObjectInput`.
   - Issue: https://github.com/kubernetes-sigs/cluster-api/issues/8395
   - `ssa.FilterObjectInput` is introduced in #8060 and can replace `helperOptions`. 
   - Ref: https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1116903390
- [ ] Rename ssa util functions:
   - Issue: https://github.com/kubernetes-sigs/cluster-api/issues/8396
   - `IsAllowedPath` -> `IsPathAllowed` ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119200006))
   - `IsIgnorePath` -> `IsPathIgnored` ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119201340))
   - Evaluate semantics of `IsNotAllowed` ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119200893))
---

**Comment by sbueringer** [comment]
Q: (not 100% sure). As of today rolloutAfter is not implement for MachineDeployments. Because of that we recommend folks to "make an arbitrary change to its spec.template" or use `clusterctl alpha rollout restart machinedeployment/my-md-0` ([link](https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html?highlight=rolloutAfter#how-to-schedule-a-machine-rollout)). `clusterctl alpha rollout restart machinedeployment/my-md-0` depends on that an [annotation change](https://github.com/kubernetes-sigs/cluster-api/blob/3802aa8483183bff90547371121f8a1567cb0c65/cmd/clusterctl/client/alpha/rollout_restarter.go#L53) triggers a rollout which actually replaces machines.

Does this mean to avoid breaking this behavior part of this effort will be to implement `rolloutAfter` for MachineDeployments + modifying `clusterctl alpha rollout restart machinedeployment/my-md-0` accordingly? I'm not sure if after in-place mutation there are other fields that we could modify instead.

**Comment by sbueringer** [comment]
Q: Do we have to track the following as well?

> In order to prevent this we are modifying the MachineDeployment controller in order to pick the "semantically equal" MachineSet with more Machines, thus avoiding or minimizing turbulence in the Cluster.
> https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20221003-In-place-propagation-of-Kubernetes-objects-only-changes.md#machinedeployment-rollouts

**Comment by fabriziopandini** [comment]
Another thing that must be considered is if to apply in-place propagation to the new/current machine set only or to old machine sets as well

**Comment by sbueringer** [comment]
> Another thing that must be considered is if to apply in-place propagation to the new/current machine set only or to old machine sets as well

That's a very good point. I think if we apply it to old MachineSets as well it would essentially break the history/rollback functionality?

**Comment by ykakarap** [comment]
> Q: (not 100% sure). As of today rolloutAfter is not implement for MachineDeployments. Because of that we recommend folks to "make an arbitrary change to its spec.template" or use `clusterctl alpha rollout restart machinedeployment/my-md-0` ([link](https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html?highlight=rolloutAfter#how-to-schedule-a-machine-rollout)). `clusterctl alpha rollout restart machinedeployment/my-md-0` depends on that an [annotation change](https://github.com/kubernetes-sigs/cluster-api/blob/3802aa8483183bff90547371121f8a1567cb0c65/cmd/clusterctl/client/alpha/rollout_restarter.go#L53) triggers a rollout which actually replaces machines.
> 
> Does this mean to avoid breaking this behavior part of this effort will be to implement `rolloutAfter` for MachineDeployments + modifying `clusterctl alpha rollout restart machinedeployment/my-md-0` accordingly? I'm not sure if after in-place mutation there are other fields left that we could modify instead.
> 
> xrefs:
> 
> * currently open PR to implement MD rolloutAfter: [✨ Implement MachineDeployment rolloutAfter support #7053](https://github.com/kubernetes-sigs/cluster-api/pull/7053)

Do not have an answer for this yet but had a similar question in the kcp rollout PR (Ref: https://github.com/kubernetes-sigs/cluster-api/pull/6858#pullrequestreview-1207368391).

One thing to consider while using RolloutAfter for triggering manual rollouts is that if a user has already set a RolloutAfter value to a later time we would be overriding that value and the original information will be lost. 
We should take a step back and look at how we want to trigger manual rollouts for both KCP and MDs. 


Also, how about tracking this discussion in a dedicated issue?

**Comment by sbueringer** [comment]
> One thing to consider while using RolloutAfter for triggering manual rollouts is that if a user has already set a RolloutAfter value to a later time we would be overriding that value and the original information will be lost.

That's a question for the clusterctl PR right?

My concern is mostly that if we rollout everything without propagation we will break the feature that folks are **able** to trigger rollouts of MachineDeployments. This is why I wonder if the implementation of MD.spec.rolloutAfter is a blocker for this issue.

If I understand correclty implementing this issue without MD.spec.rolloutAfter would break the existing feature of being able to rollout MDs without any "real" changes.

Feel free to move it to a separate issue.

**Comment by fabriziopandini** [comment]
@ykakarap do you mind adding https://github.com/kubernetes-sigs/cluster-api/issues/7293 to the task given that this work is complementary to #7088 for the autoscaler support in cluster class?

**Comment by ykakarap** [comment]
> @ykakarap do you mind adding #7293 to the task given that this work is complementary to #7088 for the autoscaler support in cluster class?

done

**Comment by sbueringer** [comment]
@ykakarap Thx for updating the issue, gives a great overview!

**Comment by enxebre** [comment]
@sbueringer @fabriziopandini @ykakarap e2e In-place propagation feature is breaking and potentially disruptive for existing clusters workflows. E.g automation relying on labels to trigger rolling upgrade.
How are we planning to contain disruption for existing workflows? Is the plan just to document changes/impact clearly as part of the minor release?

**Comment by sbueringer** [comment]
We are planning to implement RolloutAfter on MachineDeployments, adjust clusterctl accordingly + update the documentation (a corresponding note in the release notes also makes sense I think)

**Comment by ykakarap** [comment]
+1 to what Stefan said. Implementing `rolloutAfter` support for MachineDeployments is tracked in this umbrella issue and will be done as part of the v1.4 release.

**Comment by ykakarap** [comment]
@sbueringer @fabriziopandini Can I move all the follow-up items into a separate issues and close this?

**Comment by ykakarap** [comment]
All the follow-up items are moved into separate issues. This issue can now be closed.

/close
