### ISSUE TITLE
External variable discovery

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7985]
External variable discovery is being proposed in #7932 

This umbrella issue covers the steps proposed to implement external variable discovery in the CAPI repo. Some of these tasks, where larger effort is needed or the implementation needs clarification, may be represented by their own issues.

This list is ordered, by component and subtask, to reduce the dependencies between tasks when following it from top to bottom. Where tasks earlier in the list depend on later tasks this should be explicitly mentioned.

### Webhooks

- [x]     Allow Clusters to be created when the associated ClusterClass doesn't exist #7954
- [x]     Change variable defaulting and validation to operate on variables in ClusterClass `.status.variables` (Requires changes in ClusterClass) https://github.com/kubernetes-sigs/cluster-api/pull/8076
- [x]     Make inline a reserved name for patches defined in a ClusterClass https://github.com/kubernetes-sigs/cluster-api/pull/8025
- [x]     Update ClusterClass webhook validation to allow variable definition changes with existing Clusters. https://github.com/kubernetes-sigs/cluster-api/pull/8153

### Runtime SDK

- [x]     Add API definition for DiscoverVariables Runtime Hook https://github.com/kubernetes-sigs/cluster-api/pull/7986
- [x]     Ensure DiscoverVariables is registered by the ExtensionConfig controller.

### ClusterClass

- [x]     Add status `observedGeneration` to ClusterClass and set observedGeneration in the ClusterClass reconcile. https://github.com/kubernetes-sigs/cluster-api/pull/7987
- [x]     Add `variables` to the ClusterClass status and write all inline variables to `status.variables` https://github.com/kubernetes-sigs/cluster-api/pull/7991/
- [x]     Add a watch on ExtensionConfig for the ClusterClass reconciler https://github.com/kubernetes-sigs/cluster-api/pull/8006
- [x]     Add discoverVariablesExtension definition to ClusterClass `.spec.patches[].external` https://github.com/kubernetes-sigs/cluster-api/pull/8006
- [x]     Add call to externalVariables Extensions in the ClusterClass reconciler https://github.com/kubernetes-sigs/cluster-api/pull/8006
- [x]     Write all variables to ClusterClass `.status.variables` and dedupe variables based on their namespace. Note: https://github.com/kubernetes-sigs/cluster-api/pull/8006#discussion_r1099323258 https://github.com/kubernetes-sigs/cluster-api/pull/8107

### Cluster Topology

- [x]     Add ClusterClass-based Cluster defaulting and validation to the Cluster/Topology reconciler #7954
- [x]     Add observed generation success check to ClusterClass object early in the topology reconciler https://github.com/kubernetes-sigs/cluster-api/pull/8023
- [x]     Do variable defaulting and validation based on ClusterClass `.status.variables`. https://github.com/kubernetes-sigs/cluster-api/pull/8076
- [x]     Add namespacing to variable definitions in Cluster `.spec.topology.variables` https://github.com/kubernetes-sigs/cluster-api/pull/8031
- [x]     Add validation for cases where variable definitions change i.e. multiple variables with the same name but conflicting definitions. https://github.com/kubernetes-sigs/cluster-api/pull/8107
- [x]     Build variable list for patches from ClusterClass `.status.variables`
- [x]     Modify external patch call to send variables with the same origin as the patch - inline or patch name. builtin variables can be sent to all patches. https://github.com/kubernetes-sigs/cluster-api/pull/8128

### Testing and reference implementation
- [x]     Use external variables from test extension for patches.  https://github.com/kubernetes-sigs/cluster-api/pull/8026

## Planned for v1.4 release
- [x] Review UX and API from ClusterClass author and Cluster author perspective ref: https://github.com/kubernetes-sigs/cluster-api/pull/7991#discussion_r1092014511
    - [x] Make discoverVariable hook call implicit in the ClusterClass. i.e. specified by the generate-patches call. https://github.com/kubernetes-sigs/cluster-api/issues/8210
    - [x] Review strictness of equality checking of variables. 
    - [x] Follow up on UX for variables in status when reconciliation does not happen correctly - e.g. should old variables be used or should status.variables be empty, or only include variables from successful discoverVariables and **inline.**
- [x] Ensure managed fields work so that SSA does not cause inconsistencies. See https://github.com/kubernetes-sigs/cluster-api/pull/7954#discussion_r1090456744 .
- [x] Flake (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1629138713080500224) possibly a race condition between defaulting and validation - i.e. variable definition isn't reconciled at default time, but is reconciled at validation time. 

## Nice-to-have

- [ ] Create an index of ExtensionConfigs -> ClusterClass to quickly find all ClusterClasses using a particular ExtensionConfig.
- [ ] Add a warning to the webhooks when a Cluster can not be fully vaildated because the ClusterClass does not yet exist. This is dependent on webhook warning support being added in Controller Runtime.
- [ ] Enforce strict validation for ClusterClass-based clusters in webhook with annotation. i.e. mechanism to cause error on creation if the Cluster's associated ClusterClass does not exist.
- [ ]     Add best practice and guidance for creating variables to the Topology mutation guide in the book.
- [ ]     Add server library helper functions that allow easy definition of variables and enablement of a discoverVariables 
hook
- [ ]      Introduce unit tests for the test-extension to show how variable definitions can be tested.
- [ ]     Use settings to modify the variables returned in different tests.
- [ ] Ensure watch on ExtensionConfig correctly filters by extensions actually referenced in the ClusterClass. Requires full validation of the discoverVariablesExtension name in ClusterClass webhook to make naming convention hard.

/kind feature
/area runtime-sdk

**Comment by furkatgofurov7** [comment]
@killianmuldoon @sbueringer can we close this already? Asking because it has v1.4 milestone, so if not fully completed it may need to be moved to next milestone
