### ISSUE TITLE
Removing v1alpha3 & v1alpha4 apiVersions

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8038]
## Motivation

The last releases using v1alpha3 (v0.3.x) and v1alpha4 (v0.4.x) apiVersions have been both EOL since ~ April 2022  (~ a year). I think now it is time to have a plan to remove v1alpha3 & v1alpha4.

## Proposal

I would propose the following timeline:
* Cluster API release v1.4: Announcement of imminent apiVersions removal in v1.5 & v1.6
* Cluster API release v1.5:
  * v1alpha3: Kubernetes API server will stop serving v1alpha3
    * We will set `served` to `false` for the apiVersions in all our CRDs.
    * Then users can’t read or write with the old apiVersions anymore.
    * The API server will still be able to read and convert the old apiVersions.
    * If necessary, users can easily enable the apiVersions again by reverting `served` back to `true` on the CRD.
  * v1alpha4: no change
* Cluster API release v1.6:
  * v1alpha3: Remove v1alpha3 apiVersions
    * Drop all code related to v1alpha3 (API types, conversions, tests, …)
    * If we get feedback that folks need more time to migrate we can discuss delaying this stage by another minor release to give folks more time.
  * v1alpha4: Kubernetes API server will stop serving v1alpha4
    * Same as above
* Cluster API release v1.7:
  * v1alpha4: Remove v1alpha4 apiVersions
    * Same as above

## Tasks

Prerequisites: (have to be done for v1.4.0)
* [x] https://github.com/kubernetes-sigs/cluster-api/issues/7224
* [x] https://github.com/kubernetes-sigs/cluster-api/pull/7995
* [x] Open PR to document the removal plan: #8117

v1.4:
* [x] Mark v1alpha3 & v1alpha4 Go API types as deprecated: #8071
  * Note: The apiVersions were already deprecated before, we just forgot to mark the Go types accordingly.
* [x] Release notes should highlight the imminent removal of the apiVersions in v1.5 & v1.6

v1.5: (@killianmuldoon)
* [x] v1alpha3: Stop serving via `kubebuilder:unservedversion` https://github.com/kubernetes-sigs/cluster-api/pull/8549
* [x] Ensure clusterctl upgrade warns users if the upgrade would break them (e.g. v0.3 => v1.x (version without v1alpha3 apiVersion))

  * This should already be covered by our CRD migration code, but let's verify it.
  * This might only become relevant with v1.6 when we actually remove the apiVersion from the CRDs
* [x] Document the requirement to restart the kube-controller-manager after updating to a CAPI version which no longer serves v1alpha3 https://github.com/kubernetes-sigs/cluster-api/pull/8740
* [x] Release notes should reflect the changes and make a note of the controller-manager restart requirement.

v1.6: (@killianmuldoon)
* [x] v1alpha3: Drop all code related to v1alpha3 (API types, conversion, …) https://github.com/kubernetes-sigs/cluster-api/pull/8997
  * Wait a bit for feedback after v1.5
  * Ensure the clusterctl upgrade tests cover CRD migration
* [x] Drop the upstream kubeadmv1beta1 types https://github.com/kubernetes-sigs/cluster-api/pull/9345
* [x] v1alpha4: Stop serving via `kubebuilder:unservedversion` https://github.com/kubernetes-sigs/cluster-api/pull/8996/files
* [x] Document the requirement to restart the kube-controller-manager after updating to a CAPI version which no longer serves v1alpha4 https://github.com/kubernetes-sigs/cluster-api/pull/8740
* [x] Release notes should reflect the changes and make a note of the controller-manager restart requirement.

v1.7: (@killianmuldoon)
* [x] v1alpha4: Drop all code related to v1alpha4 (API types, conversion, …) https://github.com/kubernetes-sigs/cluster-api/pull/9939
  * Wait a bit for feedback after v1.6
* [ ] Release notes should reflect the changes

Misc:
* [x] Document that we're not testing skip-level upgrades (e.g. v1.1=>v1.3) but it should work: #8073
* [x] Add clusterctl upgrade tests to cover v1.0 => v1.latest: #8072

/kind cleanup
/area api

**Comment by sbueringer** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Comment by lentzi90** [comment]
I see no mention of how to ensure that old objects are "upgraded"?
IIRC this is automatically done when the old version is no longer in the `storedVersions` AND the object is written to the API. However, there is no guarantee that users will update their objects between releases. I.e. someone could have created a Cluster using v1alpha4, then `clusterctl upgrade` to a release that no longer supports v1alpha4 and get stuck because the cluster was still stored using v1alpha4.

One way to solve this is the [storage version migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator) (also linked from ref below). Another option would be to ensure that clusterctl takes care of it as part of `clusterctl upgrade`. I know cert-manager used their own CLI to handle this when they dropped old API versions.

Ref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#previous-storage-versions

**Comment by sbueringer** [comment]
@lentzi90 Thx for bringing this up. This is a very good point. But I think we have this covered as we ~ implemented what cert-manager has in clusterctl: https://github.com/kubernetes-sigs/cluster-api/pull/6749

**Comment by lentzi90** [comment]
Amazing! Thank you very much for this! Looks like it will even work automagically for the provider CRDs! :tada:

**Comment by chrischdi** [comment]
Due to the discussions at the CAPI SIG Meeting:

If v1.6 drops the code (which includes migration won't work anymore): 
It could also be considered as a reason to name it v2.0 instead to highlight the breaking change.

**Note:** from quickly reading the docs (especially https://main.cluster-api.sigs.k8s.io/contributing), I was **not** able to find a wording about this special case or that we should name bump the major version number.

**Comment by CecileRobertMichon** [comment]
>  I was not able to find a wording about this special case or that we should name bump the major version number.

AFAIK we follow semver so I think https://semver.org/ is enough justification

+1 for bumping to v2.0

**Comment by sbueringer** [comment]
Do we actually follow semver or are we following a Kubernetes-style versioning scheme? (they also treat their API versions totally independent of the Kubernetes version number)

**Comment by chrischdi** [comment]
> > ⚠ The project does not follow Go Modules guidelines for compatibility requirements for 1.x semver releases. 
> 
> Cluster API follows upstream Kubernetes semantic versioning. With the v1 release of our codebase, we guarantee the following:
> ...
[[0]](https://main.cluster-api.sigs.k8s.io/contributing?highlight=breaking#codebase-and-go-modules)

**Comment by CecileRobertMichon** [comment]
That's fair, I guess as long as we deprecate the APIs first it's fair game to remove them as a breaking change in a later minor version.

**Comment by fabriziopandini** [comment]
> maybe instead of doing both v1alpha3 and v1alpha4 together we should offset them by one minor release

this seems a good idea to me, with probably a little bit more work, but it seems a good compromise IMO

**Comment by sbueringer** [comment]
So v1alpha3 v1.5 + v1.6 (+ potential delay depending on feedback) and then v1alpha4 with v1.7 + v1.8 (+ potential delay depending on feedback)?

Will probably take us until mid 2024 to get there :/

**Comment by CecileRobertMichon** [comment]
How about:

- Cluster API release v1.3: Announcement of imminent apiVersions deprecation/removal (this is right now, this issue)
- Cluster API release v1.4: Kubernetes API server will stop serving v1alpha3 + v1alpha4 is marked as "deprecated" (if it's not already the case)
  - We will set served to false for v1alpha3 in all our CRDs.
  - Then users can’t read or write with v1alpha3 anymore.
  - The API server will still be able to read and convert v1alpha3.
  - If necessary, users can easily enable v1alpha3 again by reverting served back to true on the CRD.
- Cluster API release v1.5: Kubernetes API server will stop serving v1alpha4
  - Same provisions as above
  - Remove v1alpha3
    - Drop all code related to v1alpha3 (API types, conversions, tests, …)
- Cluster API release v1.6: v1alpha4 apiVersions
  - Drop all code related to v1alpha4 (API types, conversions, tests, …)
If we get feedback that folks need more time to migrate after v1.5 we can discuss delaying this stage by another minor release to give folks more time.

This way it's still the same timeline (everything done by v1.6) but we give ourselves more of a safe rollout instead of removing everything at once. Another option is to delay everything by one release (so stop serving v1alpha3 in v1.5 as planned) so everything is done by release v1.7 but I don't think we really need an extra 4 months to announce removal of v1alpha3, it's been deprecated for 2 years (!) https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#support-and-guarantees, it's more of a matter if we think we can get the work needed in time for v1.4 (by end of March).

**Comment by sbueringer** [comment]
Sounds good to me!

**Comment by cpanato** [comment]
+1

**Comment by sbueringer** [comment]
Ah no we need the fixes I mentioned above in v1.4.0 first and can start removing in v1.5

**Comment by killianmuldoon** [comment]
>https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/issues/63
Yeah - We'd need to delay the process by one release, but that sounds alright to me. It could all be done by 1.7 in this case?

**Comment by elmiko** [comment]
i'm +1 for splitting the action to remove v1alpha3, then v1alpha4 in the next release. in general the plan here lgtm

**Comment by sbueringer** [comment]
Thx for the comments. I updated the issue description accordingly.

Please take another look, thx :)

**Comment by fabriziopandini** [comment]
+1 for me!

**Comment by sbueringer** [comment]
As the plan PR is now merged. Remaining steps for the v1.4 release:
* https://github.com/kubernetes-sigs/cluster-api/issues/7224 (@killianmuldoon)
* Release notes should highlight the imminent removal of the apiVersions in v1.5 & v1.6 (@oscr)
  * => I think a few sentences in the release notes with reference to the plan [here](https://github.com/kubernetes-sigs/cluster-api/pull/8117) is sufficient

**Comment by joekr** [comment]
@sbueringer

@oscr and I discussed this and think that adding a few sentences in the release notes about this breaking change is a great first start. It might also be a good idea to call it out in the book. 

As an example 
<img width="977" alt="image" src="https://user-images.githubusercontent.com/132980/220952575-6fc5e82a-9c66-4d0b-a6d0-718c643bca03.png">

**Comment by sbueringer** [comment]
Sounds like a good idea in general, WDYT about making this a part of the [ClusterAPI documentation versions](https://cluster-api.sigs.k8s.io/#clusterapi-documentation-versions) box we already have right below?

**Comment by sbueringer** [comment]
Not sure if this is an ideal help wanted issue.
I would prefer keeping it assigned to myself.

/remove-help

I'll ask for help if I have tasks to delegate.

**Comment by sbueringer** [comment]
Perfect, thank you!

**Comment by willie-yao** [comment]
@sbueringer What are the recommended steps for providers to take when updating to CAPI 1.4.0? Now that the older API versions are deprecated, are providers expected to remove support for them before updating to 1.4.0? 

If not, we would have to suppress deprecation warnings for the older versions to avoid blocking on CI: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3298/pull-cluster-api-provider-azure-test/1639072621997854720

**Comment by sbueringer** [comment]
@willie-yao  I remember we had this discussion elsewhere. Did you get all the answers you need?

@killianmuldoon Based on you mentioning it this week, are you planning to take over the first two steps for v1.5?

**Comment by killianmuldoon** [comment]
Yup  - you can assign me for the work in v1.5 completely.

**Comment by sbueringer** [comment]
> Yup - you can assign me for the work in v1.5 completely.

Thx! Assigned you in the overview and co-assigned you to the issue.

**Comment by killianmuldoon** [comment]
Added an item to the task list around communicating the requirement to restart the controller manager in order to get deletion working after updating to a version which doesn't serve v1alpha3.

**Comment by sbueringer** [comment]
@killianmuldoon I think the last step should be unblocked now. IIRC you wanted to take over that one once you're back, right? (No rush!!)

**Comment by killianmuldoon** [comment]
Yup - I'll do a PR for this this week!

**Comment by killianmuldoon** [comment]
I think it's fine to close the issue - the release note should already be there in a basic form - i.e. with the breaking change. I think it's just important for the release team to be generally aware of it to add the extra information as was done in previous releases. 

This issue is probably too complicated to track that, but I'm not sure if the release team generally tracks information for future release notes somewhere.

**Comment by sbueringer** [comment]
@cahillsf ^^

Sounds reasonable

/close

**Comment by sbueringer** [comment]
Looks like we have to fix a link somehwere: https://github.com/sbueringer/cluster-api/actions/runs/7696026837/job/20970116673

**Comment by killianmuldoon** [comment]
I'll pick that up

**Comment by killianmuldoon** [comment]
I think something like the deprecation notice in https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.6.0 would be fine i.e. `The API version v1alpha4 has been completely removed in this release.`

Note: this would be for the minor release `v1.7.0`, not for an upcoming patch release.

**Comment by cahillsf** [comment]
Ah right right, cool sounds good thanks Killian
