### ISSUE TITLE
Tracking issue for code removal

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8190]
Goal of this issue is to audit all code in core Cluster API for Kubernetes version-specific handling and come up with an overview with which Kubernetes (and estimated Cluster API) version we can drop which code.

# Overview

## Code removed with Cluster API v1.11

PRs:
* https://github.com/kubernetes-sigs/cluster-api/pull/12303

Code:
* [x] KCP: Remove cgroup driver handling in KCP (-v1.23)
* [x] KCP: Webhook validation code to block update to (v1.19)
* [x] KCP: Webhook validation code for registry migration (v1.22-v1.25)
* [x] test/extension: Remove cgroup driver handling (-v1.23)
* [x] test/framework: Remove handling for nodeRoleOldControlPlane

## Code that can be removed with Cluster API v1.15

* [ ] Remove ssa.MigrateManagedFields introduced in https://github.com/kubernetes-sigs/cluster-api/pull/12890

## Code required for workload clusters

Note: We are going to keep the code 2 Cluster API versions longer as we don't strictly enforce the Kubernetes version support range (https://main.cluster-api.sigs.k8s.io/reference/versions#core-provider-cluster-api-controller)

### v1.28

* [x] Remove https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/clusterctl_upgrade.go#L728-L735: https://github.com/kubernetes-sigs/cluster-api/pull/13157
* [x] CRS: drop ensureKubernetesServiceCreated (https://github.com/kubernetes-sigs/cluster-api/issues/7804#issuecomment-1415598098) (replacement feature GA + 2): https://github.com/kubernetes-sigs/cluster-api/pull/13158

### v1.29

* [ ] KCP: Remove `AllowClusterAdminPermissions`

### v1.30

* [ ] Remove handling of kubeadm v1beta3 types in CABPK / KCP

### v1.35

* [ ] Remove Patch to remove InitConfiguration in KCP introduced in: https://github.com/kubernetes-sigs/cluster-api/pull/12897

### TBD

* [ ] Remove handling for `ControlPlaneKubeletLocalMode` feature gate
* [ ] Remove old versions in CAPD kind mapping

### v1.32

* [ ] Start using CEL format library (e.g. qualifiedName for taint key & value) (https://github.com/kubernetes/kubernetes/blob/bd11e52bfc10b9b08edbc43cd0c83458f38634f2/staging/src/k8s.io/apiserver/pkg/cel/environment/base.go#L146)

* [ ] When v1.32 (?) is our min supported mgmt cluster version we should replace some of our Pattern validation with CEL (e.g. RFC 1123 label/subdomain): https://github.com/kubernetes-sigs/cluster-api/pull/12235#discussion_r2095705757 (helps to avoid mistakes in the regexp patterns) => Let's verify that additionally with a manual test

### v1.34

* [ ] When v1.34 (?) is our min supported mgmt cluster version we should evalute if we can use `k8s-short-name` and `k8s-long-name` (https://github.com/kubernetes/kubernetes/pull/132504, https://github.com/kubernetes/kubernetes/pull/133894)

/kind cleanup

**Comment by sbueringer** [comment]
I intentionally added this to the v1.5 milestone as we won't start this activity before then and it would be good to have for v1.5

**Comment by sbueringer** [comment]
/remove-help

I'll be working on this one
