### ISSUE TITLE
Tasks for v1.5 release cycle

### ISSUE THREAD

**Issue by joekr** [kubernetes-sigs/cluster-api#8429]
Please see the corresponding section in [release-tasks.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.
* The following is based on the v1.4 release cycle. Modify according to the tracked release cycle.

Week -3 to 1:
* [x] [Release Lead] [Set a tentative release date for the minor release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#set-a-tentative-release-date-for-the-minor-release)
* [x] [Release Lead] [Assemble release team](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#assemble-release-team)

Week 1:
* [x] [Release Lead] [Finalize release schedule and team](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#finalize-release-schedule-and-team)
* [x] [Release Lead] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
* [x] [Communications Manager] [Add docs to collect release notes for users and migration notes for provider implementers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers)
* [x] [Communications Manager] [Update supported versions](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions)

Week 1 to 4:
* [x] [Release Lead] [Track] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-remove-previously-deprecated-code)

Week 6:
* [x] [Release Lead] [Cut the v1.4.2 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 9:
* [x] [Release Lead] [Cut the v1.4.3 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 11 to 12:
* [x] [Release Lead] [Track] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-bump-dependencies)

Week 13:
* [x] [Release Lead] [Cut the v1.5.0-beta.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.4.4 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Create a new GitHub milestone for the next release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-new-github-milestone-for-the-next-release)
* [x] [Release Lead] cut issues to providers to inform them to test against 1.5.0

Week 14:
* [x] [Release Lead] [Cut the v1.5.0-beta.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Select release lead for the next release cycle

Week 15:
* [x] [Release Lead] [Create the release-1.5 release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-a-release-branch)
* [x] [Release Lead] [Cut the v1.5.0-rc.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [CI Manager] [Setup jobs and dashboards for the release-1.4 release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch)
* [x] [Communications Manager] [Ensure the book for the new release is available](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#ensure-the-book-for-the-new-release-is-available)

Week 15 to 17:
* [x] [Communications Manager] [Polish release notes](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#polish-release-notes)

Week 16:
* [x] [Release Lead] [Cut the v1.5.0-rc.1 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)

Week 17:
* [x] [Release Lead] [Cut the v1.5.0 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] [Cut the v1.4.6 release](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [x] [Release Lead] Organize release retrospective
* [x] [Communications Manager] [Change production branch in Netlify to the new release branch](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#change-production-branch-in-netlify-to-the-new-release-branch)
* [x] [Communications Manager] [Update clusterctl links in the quickstart](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-clusterctl-links-in-the-quickstart)

Continuously:
* [Release lead] [Maintain the GitHub release milestone](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-maintain-the-github-release-milestone)
* [Release lead] [Bump the Go version](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bump-the-go-version)
* [Communications Manager] [Communicate key dates to the community](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-communicate-key-dates-to-the-community)
* [Communications Manager] Improve release process documentation
* [Communications Manager] Maintain and improve user facing documentation about releases, release policy and release calendar
* [CI Manager] [Monitor CI signal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-monitor-ci-signal)
* [CI Manager] [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)
* [CI Manager] [Bug triage](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bug-triage)
* [CI Manager] Maintain and improve release automation, tooling & related developer docs

If and when necessary:
* [x] [Release Lead] [Track] [Bump the Cluster API apiVersion](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-bump-the-cluster-api-apiversion)
* [x] [Release Lead] [Track] [Bump the Kubernetes version](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#optional-track-bump-the-kubernetes-version)

**Comment by sbueringer** [comment]
@joekr Follow-up to Wednesday. I also check "[Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-remove-previously-deprecated-code)". I think we're fine for this release

**Comment by Prajyot-Parab** [comment]
[Communications Manager] [Ensure the book for the new release is available](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#ensure-the-book-for-the-new-release-is-available)
PR - https://github.com/kubernetes/k8s.io/pull/5541

**Comment by sbueringer** [comment]
Updated the tasks above.

**Comment by sbueringer** [comment]
All done, thx everyone!

/close

(let me know if we missed something)

**Comment by chrischdi** [comment]
/reopen

I think we missed some parts in the release-tasks.md: 
* [Update supported versions
](https://github.com/kubernetes-sigs/cluster-api/blob/ce33c290a8a6e01b8441ee59e8c2ab0b9320aa0f/docs/release/release-tasks.md#update-supported-versions)
  * Which should be similar to what was done in https://github.com/kubernetes-sigs/cluster-api/pull/8308 . 
* the table in [CONTRIBUTING.md](https://github.com/kubernetes-sigs/cluster-api/blob/ce33c290a8a6e01b8441ee59e8c2ab0b9320aa0f/CONTRIBUTING.md?plain=1#L164) should also get an update.

I think we could also improve our release-tasks docs for this two points :-)

cc @furkatgofurov7 (as current release lead)

**Comment by furkatgofurov7** [comment]
> /reopen
> 
> I think we missed some parts in the release-tasks.md:
> 
> * [Update supported versions
>   ](https://github.com/kubernetes-sigs/cluster-api/blob/ce33c290a8a6e01b8441ee59e8c2ab0b9320aa0f/docs/release/release-tasks.md#update-supported-versions)
>   
>   * Which should be similar to what was done in [📖 docs: update CAPI support and guarantees #8308](https://github.com/kubernetes-sigs/cluster-api/pull/8308) .
> * the table in [CONTRIBUTING.md](https://github.com/kubernetes-sigs/cluster-api/blob/ce33c290a8a6e01b8441ee59e8c2ab0b9320aa0f/CONTRIBUTING.md?plain=1#L164) should also get an update.
> 
> 
> cc @furkatgofurov7 (as current release lead)

@chrischdi thanks for spotting this, there is an open PR already that tackles both of these for 1.6 release cycle: https://github.com/kubernetes-sigs/cluster-api/pull/9119/files. 

Have not gone through it yet, but I think we could make sure that, missing parts for 1.5 could be also covered in the same PR. 

> I think we could also improve our release-tasks docs for this two points :-)

+1. 
/cc @g-gaston FYI

**Comment by fabriziopandini** [comment]
Should this be closed now?

**Comment by furkatgofurov7** [comment]
@chrischdi can we close it now, your points should be covered now in https://github.com/kubernetes-sigs/cluster-api/pull/9119?

**Comment by joekr** [comment]
If not now we will be sure to close it at our meeting to discuss the v1.6 release tasks.
