### ISSUE TITLE
Tasks to bump to Kubernetes v1.27

### ISSUE THREAD

**Issue by joekr** [kubernetes-sigs/cluster-api#8459]
This issue is tracking the tasks that should be implemented **after** the Kubernetes minor release has been released.

## Tasks

Prerequisites:
* [x] Decide which Cluster API release series will support the new Kubernetes version
  * If feasible we usually cherry-pick the changes back to the latest release series.
  * We will cherry-pick into release-v1.4. Which means v1.4.x and v1.5.0 will support v1.27.

### Supporting managing and running on the new Kubernetes version (@furkatgofurov7)

This section contains tasks to update our book, e2e testing and CI to use and test the new Kubernetes version
as well as changes to Cluster API that we might have to make to support the new Kubernetes version. All of these
changes should be cherry-picked to all release series that will support the new Kubernetes version.

* [x] Modify quickstart and CAPD to use the new Kubernetes release:
  * Bump the Kubernetes version in:
    * `test/*`: search for occurrences of the previous Kubernetes version
    * `Tiltfile`
  * Ensure the latest available kind version is used (including the latest images for this kind release)
  * Verify the quickstart manually
  * Prior art: #7156
  * bump `InitWithKubernetesVersion` in `clusterctl_upgrade_test.go`
  * PRs:
    * https://github.com/kubernetes-sigs/cluster-api/pull/8518
    * https://github.com/kubernetes-sigs/cluster-api/pull/8538
* [x] Ensure the jobs are adjusted to provide test coverage according to our [support policy](https://cluster-api.sigs.k8s.io/reference/versions.html#supported-kubernetes-versions):
  * For the main branch and the release branch of the latest supported Cluster API minor release:
    * Add new periodic upgrade job.
    * Adjust presubmit jobs so that we have the latest upgrade jobs available on PRs.
  * For the main branch:
    * periodics & presubmits: 
      * Bump `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` of the `test-mink8s` jobs to the new minimum supported management cluster version.
    * periodics:
      * Bump `KUBERNETES_VERSION_MANAGEMENT` of the `e2e-mink8s` job to the new minimum supported management cluster version.
      * Drop the oldest upgrade job as the oldest Kubernetes minor version is now out of support.
  * Prior art: https://github.com/kubernetes/test-infra/pull/27421
  * PR: https://github.com/kubernetes/test-infra/pull/29295
* [x] Update book:
  * Update supported versions in `versions.md`
    * https://github.com/kubernetes-sigs/cluster-api/pull/8520
    * https://github.com/kubernetes-sigs/cluster-api/pull/8539
  * Update job documentation in `jobs.md`
    * https://github.com/kubernetes-sigs/cluster-api/pull/8521
    * https://github.com/kubernetes-sigs/cluster-api/pull/8537
  * Prior art: #7194 #7196
* [x] Issues specific to the Kubernetes minor release:
  * Sometimes there are adjustments that we have to make in Cluster API to be able to support
    a new Kubernetes minor version. Please add these issues here when they are identified.

### Using new Kubernetes dependencies (@Prajyot-Parab)

This section contains tasks to update Cluster API to use the latest Kubernetes Go dependencies and related topics
like using the right Go version and build images. These changes are only made on the main branch. We don't
need them in older releases as they are not necessary to manage workload clusters of the new Kubernetes version or
run the Cluster API controllers on the new Kubernetes version.

* [x] Ensure there is a new controller-runtime minor release which uses the new Kubernetes Go dependencies.
* [x] Update our Prow jobs for the `main` branch to use the correct `kubekins-e2e` image
  * It is recommended to have one PR for presubmit and one for periodic jobs to reduce the risk of breaking the periodic jobs.
  * Prior art: presubmit jobs: https://github.com/kubernetes/test-infra/pull/27311
  * Prior art: periodic jobs: https://github.com/kubernetes/test-infra/pull/27326
  * presubmit jobs PR: https://github.com/kubernetes/test-infra/pull/29313
  * periodic jobs PR: https://github.com/kubernetes/test-infra/pull/29314
* [x] Bump the Go version in Cluster API: (if Kubernetes is using a new Go minor version)
  * Search for the currently used Go version across the repository and update it
  * We have to at least modify it in: `hack/ensure-go.sh`, `.golangci.yml`, `cloudbuild*.yaml`, `go.mod`, `Makefile`, `netlify.toml`, `Tiltfile`
  * Prior art: #7135
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/8527
* [x] Bump controller-runtime (@sbueringer)
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/8007
* [x] Bump controller-tools
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/8581
* [x] Bump the Kubernetes version used in integration tests via `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile`
  * **Note**: This PR should be cherry-picked as well. It is part of this section as it depends on kubebuilder/controller-runtime
    releases and is not strictly necessary for [Supporting managing and running on the new Kubernetes version](#supporting-managing-and-running-on-the-new-kubernetes-version).
  * Prior art: #7193
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/8599
* [x] Bump conversion-gen via `CONVERSION_GEN_VER` in `Makefile`
  * Prior art: #7118
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/8570

**Comment by furkatgofurov7** [comment]
I can take care of it

/assign

**Comment by killianmuldoon** [comment]
IMO we shouldn't assign this issue as a whole - given there's a bunch of separate parts it might make it tougher to keep track of.  @furkatgofurov7  - do you want to take the first section i.e. all points under `Supporting managing and running on the new Kubernetes version` which can be done on release?

**Comment by furkatgofurov7** [comment]
@killianmuldoon thanks sure, I did not think of a possible complication, let's break it down then into parts and work on them separately.

**Comment by killianmuldoon** [comment]
Thanks @furkatgofurov7! Just want to make sure we don't miss stuff as it comes up 🙂

**Comment by Prajyot-Parab** [comment]
@joekr I can take care of, `Using new Kubernetes dependencies` section.

**Comment by furkatgofurov7** [comment]
@Prajyot-Parab hey, I am planning to work on the first section `Supporting managing and running on the new Kubernetes version` iteams, and you are welcome to pick the whole second section (`Using new Kubernetes dependencies`) you mentioned already.

**Comment by furkatgofurov7** [comment]
FYI, kubernetes v1.27 is [live](https://github.com/kubernetes/kubernetes/releases/tag/v1.27.0) now and we can start working on this issue.

**Comment by sbueringer** [comment]
Please (also) assign me for reviews of the PRs outside of the core CAPI repository (probably only test-infra). I'll see the PRs in core CAPI anyway, but I would also like to review the ones in test-infra.

**Comment by sbueringer** [comment]
About the prereq:
> Decide which Cluster API release series will support the new Kubernetes version
> * If feasible we usually cherry-pick the changes back to the latest release series.

Based on our policy
> When a new Kubernetes minor release is available, we will try to support it in an upcoming Cluster API patch release (although only in the latest supported Cluster API minor release)

I think we should only cherry-pick into release-v1.4. Which means v1.4.x and v1.5.0 will support v1.27.

**Comment by joekr** [comment]
I'm going to slowly start moving these long running release tasks into a release project https://github.com/orgs/kubernetes-sigs/projects/37/views/1. This way we can hand over outstanding issues instead of creating a new tracking issue for each release. This will also allow folks to update tasks. Then once they are ready to work them or need to open a discussion we can convert to issues easier than a single issue owner.

**Comment by sbueringer** [comment]
I'm not sure I understand, we have distinct tasks for each new Kubernetes bump. In which way are these tasks long running and have to be handed over?

**Comment by furkatgofurov7** [comment]
> I'm not sure I understand, we have distinct tasks for each new Kubernetes bump. In which way are these tasks long running and have to be handed over?

Agree, most probably the comment more relevant to the tracking issue where we have improvement tasks but not this one.

**Comment by furkatgofurov7** [comment]
> Please (also) assign me for reviews of the PRs (on the PRs) outside of the core CAPI repository (probably only test-infra). I'll see the PRs in core CAPI anyway, but I would also like to review the ones in test-infra.

@sbueringer PTAL at https://github.com/kubernetes/test-infra/pull/29295 whenever you have some spare time, thanks!

**Comment by sbueringer** [comment]
I would definitely like to not lose the clarity and traceability (also going forward) that this umbrella issue provides.

**Comment by sbueringer** [comment]
> > Please (also) assign me for reviews of the PRs (on the PRs) outside of the core CAPI repository (probably only test-infra). I'll see the PRs in core CAPI anyway, but I would also like to review the ones in test-infra.
> 
> @sbueringer PTAL at [kubernetes/test-infra#29295](https://github.com/kubernetes/test-infra/pull/29295) whenever you have some spare time, thanks!

Thx for the ping, on my list!

**Comment by sbueringer** [comment]
@Prajyot-Parab If it's okay for you I would like to continue the work on "Bump controller-runtime" that I started a while back here: https://github.com/kubernetes-sigs/cluster-api/pull/8007

**Comment by Prajyot-Parab** [comment]
FYI there is already a PR to upgrade k8s to v0.27 in `kubernetes-sigs/controller-runtime` - https://github.com/kubernetes-sigs/controller-runtime/pull/2189 (@joekr we will have a minor release post merge of this one for controller-runtime or do we need to discuss/take care of that ourselves?)

**Comment by joekr** [comment]
> > I'm not sure I understand, we have distinct tasks for each new Kubernetes bump. In which way are these tasks long running and have to be handed over?
> 
> Agree, most probably the comment more relevant to the tracking issue where we have improvement tasks but not this one.

yes sorry. My comment was meant for the improvement issue not this one.

**Comment by joekr** [comment]
> FYI there is already a PR to upgrade k8s to v0.27 in `kubernetes-sigs/controller-runtime` - [kubernetes-sigs/controller-runtime#2189](https://github.com/kubernetes-sigs/controller-runtime/pull/2189) (@joekr we will have a minor release post merge of this one for controller-runtime or do we need to discuss/take care of that ourselves?)

unless folks think we need it I would think we would pick this up as part of the patch releases on may 2nd.

**Comment by sbueringer** [comment]
I think we're mixing up a few things.

* "Supporting managing and running on the new Kubernetes version" the task that Furkat is working on provides support for 1.27 
  * This work is making good progress and we can see if it makes it in time for v1.4.2
  * It's 100% independent of anything in Using new Kubernetes dependencies
* "Using new Kubernetes dependencies" that Prajyot is working on depends (in part) on the controller-runtime release which isn't out yet
  * ~ all of this will only be done on main and not cherry-pick into 1.4 at all

**Comment by Prajyot-Parab** [comment]
presubmit jobs - https://github.com/kubernetes/test-infra/pull/29313
periodic jobs - https://github.com/kubernetes/test-infra/pull/29314

**Comment by furkatgofurov7** [comment]
> Ideally we have someone who ensures the umbrella issue (aka the top-level issue description) is always up-to-date, by linking the opened PRs and checking the completed tasks. (this also includes verifying that we cherry-pick everything into the appropriate branches)

Alright, @sbueringer @joekr folks here is a list of PRs' we need to link in the umbrella issue description and I need your help with:

- Modify quickstart and CAPD to use the new Kubernetes release:

  -  PR: https://github.com/kubernetes-sigs/cluster-api/pull/8518
  - PR 1.4: https://github.com/kubernetes-sigs/cluster-api/pull/8538
- Ensure the jobs are adjusted to provide test coverage according to our [support policy](https://cluster-api.sigs.k8s.io/reference/versions.html#supported-kubernetes-versions):
     - PR: https://github.com/kubernetes/test-infra/pull/29295
- Update book:
  - Update supported versions in versions.md:
       -  PR: https://github.com/kubernetes-sigs/cluster-api/pull/8520
       - PR 1.4: https://github.com/kubernetes-sigs/cluster-api/pull/8539
  - Update job documentation in jobs.md
       - PR: https://github.com/kubernetes-sigs/cluster-api/pull/8521
       - PR 1.4: https://github.com/kubernetes-sigs/cluster-api/pull/8537

**Comment by joekr** [comment]
WOW! @furkatgofurov7 this is amazing! Thank you so much for driving these to completion.

**Comment by Prajyot-Parab** [comment]
Using new Kubernetes dependencies

* Update Prow jobs for the main branch to use the correct kubekins-e2e image
  * presubmit jobs PR: https://github.com/kubernetes/test-infra/pull/29313
  * periodic jobs PR: https://github.com/kubernetes/test-infra/pull/29314

* Bump the Go version in Cluster API
  * PR: https://github.com/kubernetes-sigs/cluster-api/pull/8527

**Comment by odvarkadaniel** [comment]
Hey folks, I am working on bumping `openshift/machine-api-operator` to 1.27, but we are dependant on cluster-api, so I am blocked. Is a bump to 1.27 for capi already scheduled? I don't see it in this issue - shall I create a new issue for that? 
Thanks! :-)

**Comment by killianmuldoon** [comment]
@odvarkadaniel CAPI currently supports workload clusters on v1.27, but the underlying Kubernetes libraries have not been bumped yet. We'll do that once controller runtime releases a version that uses the underlying Kubernetes libraries as stated in the checklist in this issue under **_Using new Kubernetes dependencies_**. 

Is this the update that's blocking you?

**Comment by odvarkadaniel** [comment]
Thanks for pointing me to the right item in the list, @killianmuldoon.
Yes, I am talking about the controller-runtime update and the other underlying k8s packages in `go.mod` that CAPI is using.

**Comment by sbueringer** [comment]
@Prajyot-Parab 

Probably tracked somewhere else but "Bump the Go version in Cluster API: (if Kubernetes is using a new Go minor version)" is not completed yet.

After we got the new image for cloudbuild (https://github.com/kubernetes/test-infra/pull/29357) we have to bump the image in our cloud build YAMLs in CAPI to `v20230424-910a2a439d`

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab
> 
> Probably tracked somewhere else but "Bump the Go version in Cluster API: (if Kubernetes is using a new Go minor version)" is not completed yet.
> 
> After we got the new image for cloudbuild ([kubernetes/test-infra#29357](https://github.com/kubernetes/test-infra/pull/29357)) we have to bump the image in our cloud build YAMLs in CAPI to `v20230424-910a2a439d`
> 
> General comment. The second section can be also completed afaik apart from the controller-runtime / controller-tools tasks, but we don't have to wait for them

* PR: https://github.com/kubernetes-sigs/cluster-api/pull/8570

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab do you have time to open a PR to bump KUBEBUILDER_ENVTEST_KUBERNETES_VERSION?

sure!

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab do you have time to open a PR to bump KUBEBUILDER_ENVTEST_KUBERNETES_VERSION?

Do we need to cherry pick this one as mentioned in the description, If yes then in which release branches?

**Comment by joekr** [comment]
I believe all that work will be done in main only as we aren't making controller-runtime changes to other branches that I'm aware of.

I can update the description and remove that. If we need to cherry pick it we can do that later with a command on the PR later.

**Comment by sbueringer** [comment]
> Note: This PR should be cherry-picked as well. It is part of this section as it depends on kubebuilder/controller-runtime
releases and is not strictly necessary for Supporting managing and running on the new Kubernetes version.

It should be cherrypicked into 1.4. The idea is to run our tests against the newest kubernetes version that we support

**Comment by sbueringer** [comment]
Thx everyone. This is now comlpeted as we merged the CR bump.

/close 
:tada:
