### ISSUE TITLE
Tasks to bump to Kubernetes v1.28

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#8708]
This issue is tracking the tasks that should be implemented **after** the Kubernetes minor release has been released.

## Tasks

Prerequisites:
* [x] Decide which Cluster API release series will support the new Kubernetes version
  * If feasible we usually cherry-pick the changes back to the latest release series.
  * => As usuall will implement on main and cherry-pick into release-1.5

### Supporting managing and running on the new Kubernetes version

This section contains tasks to update our book, e2e testing and CI to use and test the new Kubernetes version
as well as changes to Cluster API that we might have to make to support the new Kubernetes version. All of these
changes should be cherry-picked to all release series that will support the new Kubernetes version.

* [x] Modify quickstart and CAPD to use the new Kubernetes release: https://github.com/kubernetes-sigs/cluster-api/pull/9160
  * Bump the Kubernetes version in:
    * `test/*`: search for occurrences of the previous Kubernetes version
    * `Tiltfile`
  * Ensure the latest available kind version is used (including the latest images for this kind release)
  * Verify the quickstart manually
  * Prior art: #7156
  * bump `InitWithKubernetesVersion` and `WorkloadKubernetesVersion` in `clusterctl_upgrade_test.go`
* [x] Ensure the jobs are adjusted to provide test coverage according to our [support policy](https://cluster-api.sigs.k8s.io/reference/versions.html#supported-kubernetes-versions): https://github.com/kubernetes/test-infra/pull/30347
  * For the main branch and the release branch of the latest supported Cluster API minor release:
    * Add new periodic upgrade job.
    * Adjust presubmit jobs so that we have the latest upgrade jobs available on PRs.
  * For the main branch:
    * periodics & presubmits: 
      * Bump `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` of the `test-mink8s` jobs to the new minimum supported management cluster version.
    * periodics:
      * Bump `KUBERNETES_VERSION_MANAGEMENT` of the `e2e-mink8s` job to the new minimum supported management cluster version.
      * Drop the oldest upgrade job as the oldest Kubernetes minor version is now out of support.
  * Prior art: https://github.com/kubernetes/test-infra/pull/27421
* [x] Update book: https://github.com/kubernetes-sigs/cluster-api/pull/9161
  * Update supported versions in `versions.md`
  * Update job documentation in `jobs.md`
  * Prior art: #7194 #7196
* [x] Issues specific to the Kubernetes minor release:
  * Sometimes there are adjustments that we have to make in Cluster API to be able to support
    a new Kubernetes minor version. Please add these issues here when they are identified.
  * [x] Check and update the Kubernetes version skew policy in the MachineSet preflight checks. #9222 
     * More details: https://github.com/kubernetes-sigs/cluster-api/pull/8595#discussion_r1195450379 

### Using new Kubernetes dependencies

This section contains tasks to update Cluster API to use the latest Kubernetes Go dependencies and related topics
like using the right Go version and build images. These changes are only made on the main branch. We don't
need them in older releases as they are not necessary to manage workload clusters of the new Kubernetes version or
run the Cluster API controllers on the new Kubernetes version.

* [x] Ensure there is a new controller-runtime minor release which uses the new Kubernetes Go dependencies.
* [x] Update our Prow jobs for the `main` branch to use the correct `kubekins-e2e` image https://github.com/kubernetes/test-infra/pull/30461 https://github.com/kubernetes/test-infra/pull/30462
  * It is recommended to have one PR for presubmit and one for periodic jobs to reduce the risk of breaking the periodic jobs.
  * Prior art: presubmit jobs: https://github.com/kubernetes/test-infra/pull/27311
  * Prior art: periodic jobs: https://github.com/kubernetes/test-infra/pull/27326
* [x] Bump the Go version in Cluster API: (if Kubernetes is using a new Go minor version) (does not apply)
  * Search for the currently used Go version across the repository and update it
  * We have to at least modify it in: `hack/ensure-go.sh`, `.golangci.yml`, `cloudbuild*.yaml`, `go.mod`, `Makefile`, `netlify.toml`, `Tiltfile`
  * Prior art: #7135
* [x] Bump controller-runtime #8999
* [x] Bump controller-tools #9221
* [x] Bump the Kubernetes version used in integration tests via `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile` https://github.com/kubernetes-sigs/cluster-api/pull/9268
  * **Note**: This PR should be cherry-picked as well. It is part of this section as it depends on kubebuilder/controller-runtime
    releases and is not strictly necessary for [Supporting managing and running on the new Kubernetes version](#supporting-managing-and-running-on-the-new-kubernetes-version).
  * Prior art: #7193
* [x] Bump conversion-gen via `CONVERSION_GEN_VER` in `Makefile` #9267
  * Prior art: #7118

**Comment by fabriziopandini** [comment]
Thanks for starting planning work for the intake of the upcoming K8s release! 
(note, planned release date as of today is Aug 15th)

**Comment by sbueringer** [comment]
We mostly opened this issue already so we can start collecting release-specific tasks "somewhere". If someone has other release-specific tasks, please let us know :)

**Comment by chrischdi** [comment]
/assign

After talking to @sbueringer : I'll takeover the `Supporting managing and running on the new Kubernetes version` part for now.

**Comment by furkatgofurov7** [comment]
@sbueringer @chrischdi do you need help with this issue since it is in parts? If so, please let me know and we can distribute it as we did in the prev release cycle :)

**Comment by sbueringer** [comment]
Thx, I think we're good for now. IIRC Christian should have most of it already locally. For the second section I have to wait for the CR release

**Comment by sbueringer** [comment]
Would be really good if we can finish https://github.com/kubernetes-sigs/cluster-api/pull/9097 so PRs building on top are not getting too messy

**Comment by chrischdi** [comment]
I pre-created PRs for the `Supporting managing and running on the new Kubernetes version` part.

They should get merged in order and the first one depends on #9097 .

Also the first one depends on the v1.28 release getting done and on getting a kind release.

They are all marked as WIP and draft for now.

### Supporting managing and running on the new Kubernetes version

* [ ]  Modify quickstart and CAPD to use the new Kubernetes release:

  - #9160

* [ ]  Ensure the jobs are adjusted to provide test coverage according to our [support policy](https://cluster-api.sigs.k8s.io/reference/versions.html#supported-kubernetes-versions):

  - https://github.com/kubernetes/test-infra/pull/30347

* [ ]  Update book:

  - #9161

**Comment by sbueringer** [comment]
All 3 PRs are merging now. @chrischdi PTAL at cherry-picking the two non-test-infra PRs into release-1.5. I suspect they might need manual cherry-picks

**Comment by sbueringer** [comment]
No, probably a few days.

**Comment by sbueringer** [comment]
CR v0.16 was released today. Opened a few PRs for the second section:
* test-infra:
  * https://github.com/kubernetes/test-infra/pull/30461
  * https://github.com/kubernetes/test-infra/pull/30462
* bump CR
  * https://github.com/kubernetes-sigs/cluster-api/pull/8999
* bump conversion-gen
  * https://github.com/kubernetes-sigs/cluster-api/pull/9267

Now waiting on a release of the kubebuilder tools for Kubernetes 1.28 (https://kubernetes.slack.com/archives/CAR30FCJZ/p1692723835465719)

I think otherwise we should be done. Would be great if someone can double-check if I/we missed something (@killianmuldoon @chrischdi)

**Comment by furkatgofurov7** [comment]
> I think otherwise we should be done. Would be great if someone can double-check if I/we missed something

Double checked it and looks like everything is covered with above PRs 👍🏼

**Comment by sbueringer** [comment]
@furkatgofurov7 thank you!

**Comment by sbueringer** [comment]
Remaining PRs
* bump envtest binaries: https://github.com/kubernetes-sigs/cluster-api/pull/9268
  * waiting on a release of the kubebuilder tools for Kubernetes 1.28 ([kubernetes.slack.com/archives/CAR30FCJZ/p1692723835465719](https://kubernetes.slack.com/archives/CAR30FCJZ/p1692723835465719))

**Comment by sbueringer** [comment]
Next Tuesday

**Comment by furkatgofurov7** [comment]
@sbueringer looks like we can close this issue?

**Comment by sbueringer** [comment]
Yup

/close
