### ISSUE TITLE
Improvement tasks for v1.6 release cycle

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#9104]
## CI Signal/Bug Triage/Automation Manager/Team

* [ ] Automate release branch and tag creation: #7128
* [ ] https://github.com/kubernetes-sigs/cluster-api/issues/6153 (depends on upstream implementation)
* [ ] cc release team on image promotion PRs: #7487 
* [ ] cc release team on cherry-pick PRs
  * Best way to do it, is probably by extending the cherrypicker in test-infra
  * Alternative or temporary solution could be a GitHub action in the cluster-api repo
* [ ] Theoretically we can use k8s-triage to generate bug reports for flaky tests via "file bug" ([link](https://storage.googleapis.com/k8s-triage/index.html?job=periodic-cluster-api-e2e-main)). Unfortunately the issues are always filed against k/k so we have to manually copy&paste the issue text to a Cluster API repo. Let's see if we can improve k8s-triage to be able to create issues in the Cluster API repo.
* [ ] Consider implementing a tool to generate our ProwJob YAMLs to make the jobs easier to manage (@sbueringer)
  * also check if there is already something like that
* [ ] Improve the Homebrew publish process
   * Context: https://github.com/kubernetes-sigs/cluster-api/issues/6613
* [ ] Improve the Netlify access model. Right now only limit people have access to the Netlify and for doing any thing regarding Netlify the people with access have to do some manual work. There is scope to improve this, either through more automation or more shared access.

## Communications/Docs/Release Notes Manager/Team

* [ ] Define details of "Communicate key dates to the community"
* [ ] Consider adding expandable auto-generated release notes for beta and RC (non-GA) releases
* [ ] Ensure we have documentation on how to consume beta / RC releases (for users)
* [ ] Potential improvements to generating release notes that automatically have the `clusterctl:` or `E2E:` or `KCP:` against the PR titles. Currently this process is done manually. May be we can improve this my looking at the `area/xxx` label of the PR or even consider some kind of PR title validation to make sure that users provide the prefix (kind of like how they currently provide ✨ , 🌱 , etc)
* [ ] Document how to consume nightly Cluster API releases with clusterctl and with the test framework
* [ ] Update documentation to build release notes tool from main before generating notes. We don't want to use `go run` anymore. Setup make target and ensuring the same binary is run on each release branch
* [ ] Can we add a line to somewhere in the release notes task to clean these up and mention the MISSING / MULTIPLE keys? This is new in this cycle but will be really useful for the upcoming release team.

## Misc

- [ ] automate updates to specific versions of https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api after release is cut
- [ ] start using github project boards to track release improvements
* [ ] Having a team alias in the OWNER/OWNER_ALIASES file so that it could be potentially used as a single source of truth where we need to know the list of release team members - could be used in some kind of automation.
   * Example: To tag members of the release team on PR (may be auto generated) on repos outside of the kuberetens-sigs org, like kubernetes/test-infra repo.
   * Context: https://github.com/kubernetes-sigs/cluster-api/pull/7487#discussion_r1013480624
- [ ] Clearly define the CI team's scope.
- [ ] Explore the idea of "an issue triage team" - a team that is responsible for triaging issues that come into the repo.
- [ ] The release team  should review documentation at the beginning of the cycle to become aware of the existing process and tools.
- [ ] Consider expanding the team even during the release cycle to handle no-shows.
    - Setup guidelines for off-boarding.
    - Have a check-point to re-confirm with members of the release team about commitment for the rest of the release cycle.
- [ ] Doc improvement (task for onboarding/first weeks): The release team  should review documentation at the beginning of the cycle to become aware of the existing process and tools.
- [ ] Doc improvement (add a note about checkpoint): Consider expanding the team even during the release cycle to handle no-shows.
    -  Setup guidelines for off-boarding.
    - Have a check-point to re-confirm with members of the release team about commitment for the rest of the release cycle.
- [ ] Doc improvement (add a recommendation to leads tasks):Communicate and set clear expectations between the leads and the shadows about timeline and rotation.
    - Clearly communicate that we will aim for rotation of ownership.
- [ ] Doc improvement: communication guidelines
    - Public should be default - it gives visibility on the work being done, it is inclusive, it is a track of record -
    - Group DM as a safe space, but not for the actual work
- [ ] Doc improvement: consider "public release session" 
    - Suggestion: Start a zoom meeting and make it public. Let's kick start the process in the zoom meeting. If there is time to just wait for some process to complete, use the time to discuss any issues/questions or just hop back on when ready to continue.
    
**NOTE:** To be clear, this is a list of potential improvements and is meant as a backlog.
The idea is not that we have to implement all of those within the v1.6 release cycle.
It's also an umbrella issue, please create separate issues for the individual sub-tasks.
Issue is created based on https://github.com/kubernetes-sigs/cluster-api/issues/8418 to avoid ownership issues when there is a need for editing issue description, assigning it to folks, etc. To check conversations in the previous cycle improvement tasks tracking issue, refer to https://github.com/kubernetes-sigs/cluster-api/issues/8418

**Comment by furkatgofurov7** [comment]
@killianmuldoon @sbueringer @joekr while the all improvements tasks polished up now, i have only one sub task without a clear understanding what needs to be done:

 > automate updates to specific versions of https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api after release is cut

Do you have any idea what exactly needs to be done to accomplish ^ task?

**Comment by sbueringer** [comment]
I can only guess, but I think doc.crds.dev only adds a new version to the list if someone calls it once. Probably after that it's also used as "latest". I think the links in our docs/book point to "latest", e.g. https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api

**Comment by killianmuldoon** [comment]
Yeah - if I remember right this link: https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api@latest needs to be called at least once before it's cached as the base page for the repo. 

The idea of that task was to automate that update - but it might be a good idea to initially add checking that page as a task during the release process. Automation can come after documented the manual process initially.

**Comment by sbueringer** [comment]
To be honest. I'm not sure if it's worth automation clicking a link if we do it once every 4 months. Maintaining automation also comes with a cost

**Comment by furkatgofurov7** [comment]
> I can only guess, but I think doc.crds.dev only adds a new version to the list if someone calls it once. Probably after that it's also used as "latest". I think the links in our docs/book point to "latest", e.g. https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api

I do not why, but when I click the above link, I have list of CRDs from v1.4.5, should we change it to point to latest?

**Comment by furkatgofurov7** [comment]
> The idea of that task was to automate that update - but it might be a good idea to initially add checking that page as a task during the release process. Automation can come after documented the manual process initially.

@killianmuldoon is it after the release is cut when we have to check it? 

Also, talking to @joekr offline, got to know about this automation: https://github.com/oracle/cluster-api-provider-oci/blob/main/.github/workflows/release.yaml#L28-L31 

Perhaps, we could also make use of it same way?

**Comment by sbueringer** [comment]
> I do not why, but when I click the above link, I have list of CRDs from v1.4.5, should we change it to point to latest?

I have the same, I have no idea

**Comment by sbueringer** [comment]
> Perhaps, we could also make use of it same way?

Sounds okay as a very last step. I don't want to manually re-run stuff if this curl somehow fails

**Comment by killianmuldoon** [comment]
@furkatgofurov7 can you assign me to  Consider implementing a tool to generate our ProwJob YAMLs to make the jobs easier to manage 

I'll open an issue to track it

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 can you assign me to Consider implementing a tool to generate our ProwJob YAMLs to make the jobs easier to manage
> 
> I'll open an issue to track it

Sure, assigned to you @killianmuldoon

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 can you assign me to Consider implementing a tool to generate our ProwJob YAMLs to make the jobs easier to manage
> 
> I'll open an issue to track it

@killianmuldoon did you have time to open a separate issue for this, if so, can you please point me to it?

**Comment by killianmuldoon** [comment]
@furkatgofurov7 I've created and issue here: https://github.com/kubernetes-sigs/cluster-api/issues/9257

**Comment by nprokopic** [comment]
Quick sanity check question regarding `Consider adding expandable auto-generated release notes for beta and RC (non-GA) releases`.

Currently from what I see, when running `make release-notes` for a pre-release, it will just output a static text defined in the `Makefile` itself, while for a regular (GA) release it runs `go run ./hack/tools/release/notes.go`.

So IIUC, a part of the above task would be to enable running `go run ./hack/tools/release/notes.go` for beta and RC releases and generate (expandable) release notes automatically?

**Comment by sbueringer** [comment]
Yup. Something like this. In CAPV the only difference is now the additional RC disclaimer. We didn't do the expandable thing (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/Makefile#L614-L621).

I think the most important part is that the release notes are also available for beta/RC and that we have a clear signal on top that this is just a beta/RC release. If we make it expandable or not is something we can decide but it's not super important in my opinion.

**Comment by cahillsf** [comment]
@furkatgofurov7 can you add a task for ensuring the new 🚀 emoji passes the `PR verify` checks when you have a chance?  [example failed run](https://github.com/kubernetes-sigs/cluster-api/actions/runs/6304791808)

source code courtesy of Cecile ([slack comment](https://kubernetes.slack.com/archives/C8TSNPY4T/p1695677178814849?thread_ts=1695646282.865989&cid=C8TSNPY4T) and [src link](https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/master/verify/type.go))

[related PR](https://github.com/kubernetes-sigs/cluster-api/pull/9444)

**Comment by furkatgofurov7** [comment]
> 👋 @furkatgofurov7 I can take this one:
> 
> > Update documentation to build release notes tool from main before generating notes. We don't want to use go run anymore. Setup make target and ensuring the same binary is run on each release branch.
> 
> would be helpful if someone from comms team can provide a bit of context for why we are making this change as well

Thanks @cahillsf, updated the issue with your name. @g-gaston was the idea here to build the tool once from main branch and use that for release branches without needing to regenerate it separately?

**Comment by cahillsf** [comment]
👋 @furkatgofurov7 I can take this one too:
> Ensure we have documentation on how to consume beta / RC releases (for users)

Although I need to understand this a bit better myself.  I will miss the beta release cut tomorrow unfortunately but can watch the recording to catch up.

**Comment by furkatgofurov7** [comment]
> @cahillsf in any case, let's open a separate issue to track it and we can discuss the details over there

@cahillsf ^^^ 😄

**Comment by cahillsf** [comment]
👋 hey @furkatgofurov7 all `In Progress`, `To Do` issues have been added to the v1.7 project board: https://github.com/orgs/kubernetes-sigs/projects/59

feel free to close out this issue

**Comment by furkatgofurov7** [comment]
@cahillsf how about:

-  Improve the Netlify access model. Right now only limit people have access to the Netlify and for doing any thing regarding Netlify the people with access have to do some manual work. There is scope to improve this, either through more automation or more shared access
- Clearly define the CI team's scope
- Theoretically we can use k8s-triage to generate bug reports for flaky tests via "file bug" ([link](https://storage.googleapis.com/k8s-triage/index.html?job=periodic-cluster-api-e2e-main)). Unfortunately the issues are always filed against k/k so we have to manually copy&paste the issue text to a Cluster API repo. Let's see if we can improve k8s-triage to be able to create issues in the Cluster API repo
-  Automate parts of the release notes that are "constant" through a minor release by reading from some file to populate the data. For example, the supported kubernetes versions can be maintained in a file on each release branch independently.
- Format dependencies to exclude multiple bumps in the same set of release notes. For Go dependencies there's a discussion in this thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1686045243091189. For Github actions and other dependencies an alternative solution will have to be found.

they seem to be not in the GH board, which is obvious because you need either a separate issue or PR to add it to the board. Are you planning to create a separate issue in the repo and then add them to the board?
I am fine closing this issue out, just making sure we move over everything here to somewhere where we can track in the future.

**Comment by cahillsf** [comment]
Ah right good catch - I only moved over the tasks with existing issues, will cut issues for the remainder to add to the new project board

**Comment by cahillsf** [comment]
hey @furkatgofurov7 should be good here.  the only one that i did not open as issue for is:
>  Consider adding expandable auto-generated release notes for beta and RC (non-GA) releases

will bring up for discussion in our kickoff RT meeting to see if we want to formalize this as an issue

**Comment by furkatgofurov7** [comment]
> hey @furkatgofurov7 should be good here. the only one that i did not open as issue for is:
> 
> > Consider adding expandable auto-generated release notes for beta and RC (non-GA) releases
> 
> will bring up for discussion in our kickoff RT meeting to see if we want to formalize this as an issue

There is an existing issue for that already, so you can just track it: https://github.com/kubernetes-sigs/cluster-api/issues/9319

**Comment by furkatgofurov7** [comment]
Looks like everything is covered now from this tracking issue, and all open/ongoing items have been carried over to GH [board](https://github.com/orgs/kubernetes-sigs/projects/59) to be tracked, so closing this issue. Thanks @cahillsf!

/close
