### ISSUE TITLE
ClusterResourceSet could take up to 16m40s to reconcile again due to locked ClusterCache Tracker

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#9775]
### What steps did you take and what happened?

* Developed clusterctl upgrade tests for CAPV.
* During installation of a workload cluster, it times out (10m timeout) while waiting for the machines to have a `.status.nodeRef`
  * https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/clusterctl_upgrade.go#L410-L429
* This is because the ClusterResourceSet which contains the cloud-controller-manager did not get rolled out before hitting the timeout

The ClusterResourceSet controller repeatedly hits this line and returns with `ctrl.Result{Requeue: true}`:

https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/addons/internal/controllers/clusterresourceset_controller.go#L169

Because the kube-apiserver takes some time to get get reachable: this return gets hit multiple times and because it ends in a Rate Limited Queue it builds up to the maximum requeue time of 1000s (16m40s).

This could also happen in other controllers where we do also return `ctrl.Result{Requeue: true}` when hitting the `remote.ErrClusterLocked` error.

### What did you expect to happen?

CRS to rollout as soon as kube-apiserver is available and by that the test to proceed/succeed.

### Cluster API version

* Using `v1.6.0-rc.0` for the test.
* During the workload cluster creation using CAPI `v1.5.3`

### Kubernetes version

v1.28.0

### Anything else you would like to add?

Workarounds are:

* reducing the sync-period for cluster-api-controller-manager (which includes the clusterresourceset controller)
* increasing the timeout to 20m for the test.

Example of a failed test: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2517/pull-cluster-api-provider-vsphere-e2e-main/1727951432931348480

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by chrischdi** [comment]
The exponential requeue delay gets added because it returns `ctrl.Result{Requeue: true}` because this then calls `c.Queue.AddRateLimited`:

https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/internal/controller/controller.go#L341

Using `ctrl.Result{RequeueAfter: <duration>}` would not lead to the exponential rate-limit backoff.

**Comment by chrischdi** [comment]
I'll create a follow-up umbrella issue for this.

**Comment by chrischdi** [comment]
Other places where we return the same:

- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L242
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/controlplane/kubeadm/internal/controllers/controller.go#L246
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/controlplane/kubeadm/internal/controllers/controller.go#L257
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/exp/internal/controllers/machinepool_controller.go#L200
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/exp/internal/controllers/machinepool_controller.go#L218
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/internal/controllers/machine/machine_controller.go#L209
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/internal/controllers/machine/machine_controller.go#L227
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/internal/controllers/machine/machine_controller.go#L609
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/internal/controllers/machinehealthcheck/machinehealthcheck_controller.go#L179
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/internal/controllers/machineset/machineset_controller.go#L187
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/internal/controllers/topology/cluster/cluster_controller.go#L212
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go#L161
- [ ] https://github.com/kubernetes-sigs/cluster-api/blob/47bfc14141315344fe829ecad3ccb4268c3ebf79/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L198
